galaxy_info:
  author: G Derber
  description: Installs Funtoo keychain
  company: Bloodymage

  issue_tracker_url: http://github.com/bloodymage/ansible-collection-autonomy

  license: MIT

  min_ansible_version: "2.19"

  platforms:
    - name: Debian
      versions:
        - "trixie"

  galaxy_tags:
    - bloodymage
    - keychain

dependencies:
  - role: bloodymage.autonomy.common
