---
- name: "NSUPDATE: Add RPZ records."
  community.general.nsupdate:
    key_name: "{{ autonomy_common_zone_name }}"
    key_secret: "{{ __key_secret }}"
    key_algorithm: "{{ autonomy_common_dyndns_key_algorithm }}"
    server: "{{ autonomy_common_dns_primary_server_ip }}"
    zone: "{{ rpz['name'] }}"
    record: "{{ item }}.{{ rpz['name'] }}"
    value: "."
    type: "CNAME"
    state: present
  loop: "{{ rpz['records_present'] }}"
  become: false
  vars:
    __nameserver: "{{ autonomy_common_dns_primary_server_hostname }}"
    __password_store_id: "{{ autonomy_common_password_db }}/{{ autonomy_common_zone_domain }}/hosts/{{ __nameserver }}/bind_dyndns_secret"
    __password_lookup: "{{ __password_store_id }}"
    __key_secret: "{{ lookup('community.general.passwordstore', __password_lookup) }}"
    __dns_servers: "{{ autonomy_common_zone_name }}_dns_servers"
  delegate_to: localhost
  when:
    - rpz['records_present'] is defined
  tags:
    - dns
    - dns-nsupdate

- name: "NSUPDATE: Remove RPZ records."
  community.general.nsupdate:
    key_name: "{{ autonomy_common_zone_name }}"
    key_secret: "{{ __key_secret }}"
    key_algorithm: "{{ autonomy_common_dyndns_key_algorithm }}"
    server: "{{ autonomy_common_dns_primary_server_ip }}"
    zone: "{{ rpz['name'] }}"
    record: "{{ item }}.{{ rpz['name'] }}"
    value: "."
    type: "CNAME"
    state: absent
  loop: "{{ rpz['records_absent'] }}"
  when:
    - rpz['records_present'] is defined
  become: false
  vars:
    __nameserver: "{{ autonomy_common_dns_primary_server_hostname }}"
    __password_store_id: "{{ autonomy_common_password_db }}/{{ autonomy_common_zone_domain }}/hosts/{{ __nameserver }}/bind_dyndns_secret"
    __password_lookup: "{{ __password_store_id }}"
    __key_secret: "{{ lookup('community.general.passwordstore', __password_lookup) }}"
    __dns_servers: "{{ autonomy_common_zone_name }}_dns_servers"
  delegate_to: localhost
  tags:
    - dns
    - dns-nsupdate
