---
# ==================================================================================================
#
# We remove old records first because if we are changing type (CNAME -> A, or AAAA to CNAME),
# adding the record will fail.
#
# Currently supports the following Record Types:
#   - A
#   - AAAA
#   - CNAME
#   - MX
#   - TXT
#
# ==================================================================================================
- name: "Cloudflare: Get public IPv4 Address."
  community.general.ipify_facts:
    api_url: "https://api.ipify.org/"
    timeout: 10
    validate_certs: true
  tags:
    - dns
    - dns-cloudflare

- name: "Cloudflare: Remove A records."
  community.general.cloudflare_dns:
    api_token: "{{ autonomy_maintenance_cloudflare_key }}"
    zone: "{{ autonomy_common_zone_domain }}"
    record: "{{ autonomy_maintenance_cloudflare_hostname }}"
    type: "A"
    value: "{{ ipify_public_ip }}"
    comment: "{{ autonomy_maintenance_cloudflare_a_record_comment | default(omit) }}"
    state: "absent"
    proxied: "{{ autonomy_maintenance_cloudflare_proxied }}"
    timeout: "{{ autonomy_maintenance_cloudflare_timeout }}"
    ttl: "{{ autonomy_maintenance_cloudflare_ttl }}"
  become: false
  when:
    - not autonomy_maintenance_cloudflare_a_record_enabled
  tags:
    - dns
    - dns-cloudflare

- name: "Cloudflare: Remove AAAA records."
  community.general.cloudflare_dns:
    api_token: "{{ autonomy_maintenance_cloudflare_key }}"
    zone: "{{ autonomy_common_zone_domain }}"
    record: "{{ autonomy_maintenance_cloudflare_hostname }}"
    type: "AAAA"
    value: "{{ autonomy_common_ipv6_address }}"
    state: "absent"
    proxied: "{{ autonomy_maintenance_cloudflare_proxied }}"
    timeout: "{{ autonomy_maintenance_cloudflare_timeout }}"
    ttl: "{{ autonomy_maintenance_cloudflare_ttl }}"
  become: false
  when:
    - not autonomy_maintenance_cloudflare_aaaa_record_enabled
  tags:
    - dns
    - dns-cloudflare

- name: "Cloudflare: Remove CNAME records."
  community.general.cloudflare_dns:
    api_token: "{{ autonomy_maintenance_cloudflare_key }}"
    zone: "{{ item['zone'] | default(autonomy_common_zone_domain) }}"
    record: "{{ item['record'] }}"
    type: "CNAME"
    value: "{{ item['value'] }}"
    state: "absent"
    proxied: "{{ item['proxied'] | default(autonomy_maintenance_cloudflare_proxied) }}"
    timeout: "{{ autonomy_maintenance_cloudflare_timeout }}"
    ttl: "{{ autonomy_maintenance_cloudflare_ttl }}"
  loop: "{{ autonomy_maintenance_cloudflare_cname_records }}"
  become: false
  when:
    - autonomy_maintenance_cloudflare_cname_records is falsy
  tags:
    - dns
    - dns-cloudflare

- name: "Cloudflare: Add or modify A records."
  community.general.cloudflare_dns:
    api_token: "{{ autonomy_maintenance_cloudflare_key }}"
    zone: "{{ autonomy_common_zone_domain }}"
    record: "{{ autonomy_maintenance_cloudflare_hostname }}"
    type: "A"
    value: "{{ ipify_public_ip }}"
    state: "present"
    proxied: "{{ autonomy_maintenance_cloudflare_proxied }}"
    solo: "{{ autonomy_maintenance_cloudflare_solo }}"
    timeout: "{{ autonomy_maintenance_cloudflare_timeout }}"
    ttl: "{{ autonomy_maintenance_cloudflare_ttl }}"
  become: false
  when:
    - autonomy_maintenance_cloudflare_a_record_enabled
  tags:
    - dns
    - dns-cloudflare

- name: "Cloudflare: Add or modify AAAA records."
  community.general.cloudflare_dns:
    api_token: "{{ autonomy_maintenance_cloudflare_key }}"
    zone: "{{ autonomy_common_zone_domain }}"
    record: "{{ autonomy_maintenance_cloudflare_hostname }}"
    type: "AAAA"
    value: "{{ autonomy_common_ipv6_address }}"
    state: "present"
    proxied: "{{ autonomy_maintenance_cloudflare_proxied }}"
    solo: "{{ autonomy_maintenance_cloudflare_solo }}"
    timeout: "{{ autonomy_maintenance_cloudflare_timeout }}"
    ttl: "{{ autonomy_maintenance_cloudflare_ttl }}"
  become: false
  when:
    - autonomy_maintenance_cloudflare_aaaa_record_enabled
  tags:
    - dns
    - dns-cloudflare

- name: "Cloudflare: Add or modify CNAME records." # noqa: jinja[spacing]
  community.general.cloudflare_dns:
    api_token: "{{ autonomy_maintenance_cloudflare_key }}"
    zone: "{{ item['zone'] | default(autonomy_common_zone_domain) }}"
    record: "{{ item['record'] }}"
    type: "CNAME"
    value: "{{ item['value'] }}"
    state: "present"
    proxied: "{{ item['proxied'] | default(autonomy_maintenance_cloudflare_proxied) }}"
    solo: "{{ autonomy_maintenance_cloudflare_solo }}"
    timeout: "{{ autonomy_maintenance_cloudflare_timeout }}"
    ttl: "{{ autonomy_maintenance_cloudflare_ttl }}"
  loop: "{{ autonomy_maintenance_cloudflare_cname_records }}"
  become: false
  when:
    - autonomy_maintenance_cloudflare_cname_records is truthy
  vars:
    __autonomy_maintenance_proton_mail_dkim_code: >-
      {%- if autonomy_maintenance_proton_mail_dkim_code == "password" -%}
      {{ lookup('community.general.passwordstore', autonomy_maintenance_proton_mail_dkim_password_store_lookup) }}
      {%- else -%}
      {{ autonomy_maintenance_proton_mail_dkim_code }}
      {%- endif %}
  tags:
    - dns
    - dns-cloudflare

- name: "Cloudflare: Add or modify MX records."
  community.general.cloudflare_dns:
    api_token: "{{ autonomy_maintenance_cloudflare_key }}"
    zone: "{{ mx['zone'] | default(autonomy_common_zone_domain) }}"
    record: "{{ mx['record'] }}"
    type: "MX"
    value: "{{ mx['value'] }}"
    priority: "{{ __priority }}"
    state: "present"
    solo: "{{ mx['solo'] | default(false) }}"
    timeout: "{{ autonomy_maintenance_cloudflare_timeout }}"
    ttl: "{{ autonomy_maintenance_cloudflare_ttl }}"
  loop: "{{ autonomy_maintenance_cloudflare_mx_records }}"
  loop_control:
    loop_var: mx
    index_var: mx_index
  become: false
  vars:
    __priority: "{{ mx['priority'] | default(mx_index * 10) }}"
  when:
    - autonomy_maintenance_cloudflare_mx_records is truthy
  tags:
    - dns
    - dns-cloudflare

- name: "Cloudflare: Add or modify TXT records." # noqa: jinja[spacing]
  community.general.cloudflare_dns:
    api_token: "{{ autonomy_maintenance_cloudflare_key }}"
    zone: "{{ item['zone'] | default(autonomy_common_zone_domain) }}"
    record: "{{ item['record'] }}"
    type: "TXT"
    state: "present"
    value: "{{ item['value'] }}"
    timeout: "{{ autonomy_maintenance_cloudflare_timeout }}"
    ttl: "{{ autonomy_maintenance_cloudflare_ttl }}"
  loop: "{{ autonomy_maintenance_cloudflare_txt_records }}"
  become: false
  vars:
    __autonomy_maintenance_proton_mail_verification: >-
      {%- if autonomy_maintenance_proton_mail_verification == "password" -%}
      {{ lookup('community.general.passwordstore', autonomy_maintenance_proton_mail_verification_password_store_lookup) }}
      {%- else -%}
      {{ autonomy_maintenance_proton_mail_verification }}
      {%- endif %}
    __autonomy_maintenance_proton_alias_verification: >-
      {%- if autonomy_maintenance_proton_alias_verification == "password" -%}
      {{ lookup('community.general.passwordstore', autonomy_maintenance_proton_alias_verification_password_store_lookup) }}
      {%- else -%}
      {{ autonomy_maintenance_proton_alias_verification }}
      {%- endif %}


  when:
    - autonomy_maintenance_cloudflare_txt_records is truthy
  tags:
    - dns
    - dns-cloudflare
