---
- name: "Download Hagezi RPZ files."
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: absent
  loop: "{{ autonomy_common_dns_rpz_hagezi_zones }}"
  become: true
  tags:
    - dns
    - dns-file

- name: "Download Hagezi RPZ files."
  ansible.builtin.get_url:
    url: "{{ item['url'] }}"
    dest: "{{ item['path'] }}"
    #checksum: "sha512:AAA"
    owner: "{{ autonomy_common_bind_owner }}"
    group: "{{ autonomy_common_bind_group }}"
    mode: "0644"
    force: true
  loop: "{{ autonomy_common_dns_rpz_hagezi_zones }}"
  become: true
  notify: restart bind
  tags:
    - dns
    - dns-file

- name: "Flush Handlers for DNS Servers."
  ansible.builtin.meta: flush_handlers
  tags:
    - dns
    - dns-file
