---
# tasks file for maintenance
- name: Include OS-specific variables.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false
  tags:
    - dns
    - dns-nsupdate
    - dns-cloudflare
    - system_upgrade
    - system-upgrade
    - system_upgrade_debug
    - system-upgrade-debug

- name: "Include DNS Tasks."
  include_tasks: "dns.yml"
  when:
    __maintenance_tasks == "dns"
  tags:
    - maintenance
    - dns
    - dns-file
    - dns-nsupdate
    - dns-cloudflare

- name: "Include Reboot Tasks."
  include_tasks: "reboot.yml"
  when:
    __maintenance_tasks == "reboot"

- name: "Include Service Restart Tasks."
  include_tasks: "service_restart.yml"
  when:
    __maintenance_tasks == "service restart"

- name: "Include System Upgrade Tasks."
  include_tasks: "upgrade.yml"
  when:
    __maintenance_tasks == "upgrade"
  tags:
    - maintenance
    - upgrade

- name: "Include Wake-on-LAN Tasks."
  include_tasks: "wake_on_lan.yml"
  when:
    __maintenance_tasks == "wakeonlan"

- name: "Include Database Tasks."
  include_tasks: "database.yml"
  when:
    __maintenance_tasks == "database"
