---
- name: "Check for RouterOS updates."
  community.routeros.command:
    commands:
      - /system package update check-for-updates
  register: routeros_resources
  become: no
  changed_when: false
  tags:
    - system_upgrade
    - system-upgrade

- name: "Print RouterOS updates."
  ansible.builtin.debug:
    msg:
      - "Current Version 1: {{ ansible_net_version }}"
      - "Current Version 2: {{ installed_version }}"
      - "Available Version: {{ available_version }}"
      - "Status:            {{ status }}"
  vars:
    __lines: "{{ routeros_resources['stdout_lines'] }}"
    installed_version: "{{ __lines[0][5].split(':')[1].split(' ')[1] | trim }}"
    available_version: "{{ __lines[0][6].split(':')[1].split(' ')[1] | trim }}"
    status: "{{ __lines[0][7].split(':')[1] | trim }}"
  become: no
  tags:
    - system-upgrade
    - system_upgrade
