---
# handlers file for systemd_networkd
- name: "Restart Systemd-Networkd."
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - systemd-networkd
  become: true
  listen:
    - "restart systemd-networkd"
