---
# defaults file for spamassassin
autonomy_spamassassin_packages:
  - "{{ autonomy_common_spamassassin_package }}"
  - spamass-milter

autonomy_spamassassin_user_home: "{{ autonomy_common_state_dir }}/spamassassin"

autonomy_spamassassin_directories:
  - name: "{{ mail_spamassassin_sock_dir }}"
    owner: "{{ spamassassin_spamass_milter_user }}"
    group: root
    mode: "0755"
  - name: "{{ autonomy_spamassassin_user_home }}/sa-update-keys"
    owner: "{{ spamassassin_spamd_user }}"
    group: "{{ spamassassin_spamd_user }}"
    mode: "0700"

autonomy_spamassassin_default_files:
  - spamassassin
  - spamass-milter
  - spamd

autonomy_spamassassin_config_files:
  - local.cf

autonomy_spamassassin_deamon: "spamassassin"
autonomy_spamassassin_syslog_dir: ""
autonomy_spamassassin_syslog: ""
autonomy_spamassassin_debug: false
autonomy_spamassassin_max_children: 5


autonomy_spamassassin_user_shell: "{{ autonomy_common_shell_path }}"
autonomy_spamass_milter_user_home: "{{ autonomy_common_state_dir }}/spamass-milter"
autonomy_spamass_milter_user_shell: "{{ autonomy_common_syscmd_dir }}/nologin"

autonomy_spamassassin_users:
  - name: "{{ spamassassin_spamd_user }}"
    home: "{{ autonomy_spamassassin_user_home }}"
    shell: "{{ autonomy_spamassassin_user_shell }}"
  - name: "{{ spamassassin_spamass_milter_user }}"
    home: "{{ autonomy_spamass_milter_user_home }}"
    shell: "{{ autonomy_spamass_milter_user_shell }}"
    groups: "{{ spamassassin_spamd_user }}"
    append: true

autonomy_spamassassin_siteconfigpath: ""

# ==================================================================================================
#
# Spamassassin local.cf
#
# https://spamassassin.apache.org/full/3.1.x/doc/Mail_SpamAssassin_Conf.html
#
# If you wish to have this be global, set:
# autonomy_spamassassin_bayes_path: "/var/lib/spamassassin/.spamassassin/bayes"
#
# ==================================================================================================
autonomy_spamassassin_bayes_path: ""
autonomy_spamassassin_bayes_file_mod: "0700"
autonomy_spamassassin_ok_locales: "{{ __autonomy_spamassassin_ok_languages }}"

# ==================================================================================================
#
# Spamassassin Internal defaults
#
# ==================================================================================================
__autonomy_spamassassin_bayes_path: "~/.spamassassin/"
__autonomy_spamassassin_ok_locales: "all"
