#!/bin/bash

function define_colors() {

    # Define Normal Colors
    BLACK='\033[0;30m'
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    BLUE='\033[0;34m'
    MAGENTA='\033[0;35m'
    CYAN='\033[0;36m'
    WHITE='\033[0;37m'
				        
    # Define Bold Colors
    BBLACK='\033[1;30m'
    BRED='\033[1;31m'
    BGREEN='\033[1;32m'
    BYELLOW='\033[1;33m'
    BBLUE='\033[1;34m'
    BMAGENTA='\033[1;35m'
    BCYAN='\033[1;36m'
    BWHITE='\033[1;37m'

    # Define DIM Colors
    DBLACK='\033[2;30m' # Black
    DRED='\033[2;31m' # Red
    DGREEN='\033[2;32m' # Green
    BYELLOW='\033[2;33m' # Yellow
    DBLUE='\033[2;34m' # Blue
    DMAGENTA='\033[2;35m' # Purple
    DCYAN='\033[2;36m' # Cyan
    DWHITE='\033[2;37m' # White
    
    # Define Italic Colors
    IBLACK='\033[3;30m' # Black
    IRED='\033[3;31m' # Red
    IGREEN='\033[3;32m' # Green
    IYELLOW='\033[3;33m' # Yellow
    IBLUE='\033[3;34m' # Blue
    IMAGENTA='\033[3;35m' # Purple
    ICYAN='\033[3;36m' # Cyan
    IWHITE='\033[3;37m' # White

    # Define Underline Colors
    UBLACK='\033[4;30m' # Black
    URED='\033[4;31m' # Red
    UGREEN='\033[4;32m' # Green
    UYELLOW='\033[4;33m' # Yellow
    UBLUE='\033[4;34m' # Blue
    UMAGENTA='\033[4;35m' # Purple
    UCYAN='\033[4;36m' # Cyan
    UWHITE='\033[4;37m' # White

    # Define Blinking (Flashing) Colors
    FBLACK='\033[5;30m' # Black
    FRED='\033[5;31m' # Red
    FGREEN='\033[5;32m' # Green
    FYELLOW='\033[5;33m' # Yellow
    FBLUE='\033[5;34m' # Blue
    FMAGENTA='\033[5;35m' # Purple
    FCYAN='\033[5;36m' # Cyan
    FWHITE='\033[5;37m' # White

    # Define Unknown Colors
#    UBLACK='\033[6;30m' # Black
#    URED='\033[6;31m' # Red
#    UGREEN='\033[6;32m' # Green
#    UYELLOW='\033[6;33m' # Yellow
#    UBLUE='\033[6;34m' # Blue
#    UMAGENTA='\033[6;35m' # Purple
#    UCYAN='\033[6;36m' # Cyan
#    UWHITE='\033[6;37m' # White
	    
    # Define Reverse Colors
    RBLACK='\033[7;30m' # Black
    RRED='\033[7;31m' # Red
    RGREEN='\033[7;32m' # Green
    RYELLOW='\033[7;33m' # Yellow
    RBLUE='\033[7;34m' # Blue
    RMAGENTA='\033[7;35m' # Purple
    RCYAN='\033[7;36m' # Cyan
    RWHITE='\033[7;37m' # White

    # Background Colors
    On_Black='\033[40m' # Black
    On_Red='\033[41m'   # Red
    On_Green='\033[42m' # Green
    On_Yellow='\033[43m' # Yellow
    On_Blue='\033[44m'   # Blue
    On_Purple='\033[45m' # Purple
    On_Cyan='\033[46m' # Cyan
    On_White='\033[47m' # White

    # Other
    NO_COLOR='\033[0m'
    ALERT=${BWHITE}${On_Red} # Bold White on red background

    # Set Default Color
    # User color
    USERTEXT="${GREEN}"
    #hostname color
    HC="${YELLOW}"
    #regular color
    RC="${WHITE}"
    #default color
    DC=$(echo -ne ${NO_COLOR})
}

