---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ autonomy_make_packages }}"
    state: present
  become: true
