---
# ======================================================================
#
# Task "Install Common Apps"
#
# Installs a set of common apps for all systems on the network
#
# ======================================================================
- name: "Include OS-specific variables."
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false

- name: "Check to determine if we need krb5 support"
  ansible.builtin.set_fact:
    autonomy_apache_packages: "{{ autonomy_apache_packages + autonomy_apache_krb5_packages }}"
    autonomy_apache_modules: "{{ autonomy_apache_modules + autonomy_apache_kerberos_ad_sso_modules }}"
  become: false
  when:
    - inventory_hostname in groups['internal_zone']
    - autonomy_realm_identity_management_system is truthy

- name: "Check to determine if we need ldap support"
  ansible.builtin.set_fact:
    autonomy_apache_modules: "{{ autonomy_apache_modules + autonomy_apache_ldap_modules  }}"
  become: false
  when:
    - autonomy_realm_identity_management_system is truthy

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ autonomy_apache_packages }}"
    state: present
  become: true

- name: "http service state"
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  become: true

# ======================================================================
#
#
#
# ======================================================================
# - name: Configure SELinux to allow httpd to connect to remote database
#   seboolean:
#     name: httpd_can_network_connect_db
#     state: true
#     persistent: true
#   when: sestatus.rc != 0

# ======================================================================
#
#
#
# ======================================================================
- name: "Ensure file directories have proper permissions"
  ansible.builtin.file:
    path: "/srv/www"
    owner: www-data
    group: www-data
    state: directory
    recurse: true
    mode: "0755"
  become: true
