---
# ==================================================================================================
#
# GPG Sync
#
# ==================================================================================================
autonomy_gpgsync_keylist: "{{ ownca_crl_distribution_point }}/pgp/keylist.json"
autonomy_gpgsync_gpg_fingerprint: ""
