---
# defaults file for users
autonomy_users_packages: []

autonomy_users_groups:
  - name: ssl-cert
    system: true

autonomy_users_group_ansible_managed: "ansiblemanaged"
autonomy_users_managed_min_id: 1000
autonomy_users_managed_max_id: 10000

users_sudoers_options:
  - application: "screen"
    options:
      - entity: "Default"
        value: "env_keep += WINDOW"

autonomy_users_password_hash_seed: "{{ inventory_hostname }}"

# Directories
autonomy_users_base_home_dir: "{{ autonomy_common_home_dir }}"
autonomy_users_home_dir: "{{ autonomy_users_base_home_dir }}/{{ __autonomy_users_loopvar_username }}"
autonomy_users_config_dir: "{{ autonomy_users_home_dir }}/.config"
autonomy_users_data_dir: "{{ autonomy_users_home_dir }}/.local/share"
autonomy_users_state_dir: "{{ autonomy_users_home_dir }}/.local/state"
autonomy_users_cache_dir: "{{ autonomy_users_home_dir }}/.cache"

autonomy_users_password_store_dir: >-
  {% if autonomy_users_password_store_xdg_data_dir -%}
  {{ autonomy_users_data_dir }}/password-store
  {%- else -%}
  {{ autonomy_users_home_dir }}/.password-store
  {%- endif %}

# Files
autonomy_users_password_store_gpg_id_file: ".gpg-id"

# Paths
autonomy_users_password_store_gpg_id_path: "{{ autonomy_users_password_store_dir }}/{{ autonomy_users_password_store_gpg_id_file }}"

# ==================================================================================================
#
# User Dotfiles settings
#
# ==================================================================================================
autonomy_users_password_store_xdg_data_dir: false

# Misc
autonomy_users_dotfiles_users: "{{ autonomy_common_users }}"
autonomy_users_dotfiles_mode: "0700"

# ===================================================================================================
#
# Emacs Settings
#
# ==================================================================================================
autonomy_users_dotfiles_emacsd_repo: ""
autonomy_users_dotfiles_emacsd_repo_remote: "origin"
autonomy_users_dotfiles_emacsd_repo_version: "main"

# ==================================================================================================
#
#
#
# ==================================================================================================
__user_groups:
  - name: "{{ autonomy_users_group_ansible_managed }}"
    system: true
  - name: users
    system: true
  - name: wheel
    system: true

__users: "{{ autonomy_common_users }}"

__default_mikrotik_device_user: "admin"

__username_list: []

__samba_domain_groups:
  - groupname: ansiblemanaged

__realm_user_dn_list: []

__autonomy_users_loopvar_username: ""
