---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false
  tags:
    - maintenance
    - apt
    - upgrade

- name: "Update distribution repos 'debian.sources' format."
  ansible.builtin.include_tasks: "debian_sources.yml"
  vars:
    __dist_major_version: "{{ ansible_distribution_major_version | int }}"
  when:
    - __dist_major_version >= 13
  tags:
    - maintenance
    - apt
    - upgrade

- name: "Update distribution repos 'sources.list' format."
  ansible.builtin.include_tasks: "sources_list.yml"
  vars:
    __dist_major_version: "{{ ansible_distribution_major_version | int }}"
  when:
    - __dist_major_version < 13
  tags:
    - apt

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ autonomy_apt_packages }}"
    state: present
  become: true
  tags:
    - maintenance
    - apt
    - upgrade
