---
# ==================================================================================================
#
# FIXME: ansible-lint ingnore-errors
#
# This is done because it's used to check connectivity from one host to another.  If it fails, I
# want to know about it, but I also want it to continue and run other diagnostic tests.
#
# ==================================================================================================
- name: "Ping inventory hosts."
  ansible.builtin.command:
    cmd: "ping -c 1 {{ hostvars[item]['ansible_host'] }}"
  loop: "{{ groups['all'] }}"
  ignore_errors: true # noqa: ignore-errors
  tags:
    - connectivity
    - ping

# - name: "Ping from host {{ source_host }}."
#   delegate_to: "{{ source_host }}"
#   ignore_errors: true
