---
- name: "Create SSL Directories."
  ansible.builtin.file:
    path: "{{ item['name'] }}"
    owner: "{{ item['owner'] }}"
    group: "{{ item['group'] }}"
    mode: "{{ item['mode'] }}"
    state: directory
  loop: "{{ autonomy_ownca_hosts_dirs }}"
  become: false
  delegate_to: "{{ autonomy_ownca_certificate_authority_host }}"
  run_once: true

- name: "Add subject alt names based on ipv6."
  ansible.builtin.set_fact:
    autonomy_ownca_host_subject_alt_name: "{{ autonomy_ownca_host_subject_alt_name + [__alt_name] }}"
  vars:
    __alt_name: "IP:{{ autonomy_common_ipv6_address }}"
  become: false
  when:
    - autonomy_common_ipv6_address is truthy

# - name: "Add subject alt names based on role."
#   ansible.builtin.set_fact:
#     ownca_host_certs_subject_alt_name: "{{ ownca_host_certs_subject_alt_name + __alt_name }}"
#   become: false
#   loop:
#     - name: "db_servers"
#       alt_name: "db"
#     - name: "dns_servers"
#       alt_name: "ns"
#     - name: "file_servers"
#       alt_name: "fs"
#     - name: "git_servers"
#       alt_name: "git"
#     - name: "homeassistant"
#       alt_name: "home"
#     - name: "auth_servers"
#       alt_name: "auth"
#     - name: "ldap_servers"
#       alt_name: "ldap"
#     - name: "mail_servers"
#       alt_name: "mail"
#     - name: "dovecot_servers"
#       alt_name: "imap"
#     - name: "postfix_servers"
#       alt_name: "smtp"
#     - name: "dlna_servers"
#       alt_name: "dlna"
#     - name: "mosquitto_servers"
#       alt_name: "mqtt"
#     - name: "radius_servers"
#       alt_name: "radius"
#     - name: "redis_servers"
#       alt_name: "redis"
#     - name: "samba_domain_controllers"
#       alt_name: "dc"
#     - name: "web_servers"
#       alt_name: "www"
#     - name: "zwavecontrollers"
#       alt_name: "zwave"
#     - name: "routers"
#       alt_name: "router"
#   vars:
#     __group_id: "{{ autonomy_common_zone_name }}_{{ item.name }}"
#     __host_index: "{{ groups[__group_id].index(inventory_hostname) + 1 }}"
#     __padded_index: "{{ '%02d' % __host_index | int }}"
#     __alt_name:
#       - "DNS:{{ item.alt_name }}{{ __padded_index }}.{{ autonomy_common_zone_domain }}"
#       - "DNS:{{ item.alt_name }}.{{ autonomy_common_zone_domain }}"
#   when:
#     - inventory_hostname in groups[item.name] | default([])

# - name: "Add hardware based subject alt names."
#   ansible.builtin.set_fact:
#     ownca_host_certs_subject_alt_name: "{{ ownca_host_certs_subject_alt_name + __alt_name }}"
#   become: true
#   loop:
#     - name: "routers"
#       alt_name: "router"
#     - name: "printers"
#       alt_name: "printer"
#   vars:
#     __group_id: "{{ autonomy_common_zone_name }}_{{ item.name }}"
#     __host_index: "{{ groups[__group_id].index(inventory_hostname) + 1 }}"
#     __group_size: "{{ groups[__group_id] | length }}"
#     __padded_index: "{% if __group_size != 1%}{{ '%02d' % __host_index | int }}{% else %}{% endif %}"
#     __alt_name:
#       - "DNS:{{ item.alt_name }}{{ __padded_index }}.{{ autonomy_common_zone_domain }}"
#   when:
#     - inventory_hostname in groups[item.name] | default([])

- name: "Add additional subject alt names for samba domain controllers."
  ansible.builtin.set_fact:
    autonomy_ownca_host_subject_alt_name: "{{ autonomy_ownca_host_subject_alt_name + __alt_name }}"
  vars:
    __alt_name:
      - "DNS:{{ autonomy_common_zone_domain }}"
      - "otherName:{{ autonomy_ownca_msadguid_oid }};UTF8:{{ autonomy_ownca_objectguid }}"
  become: false
  when:
    - inventory_hostname in groups['samba_domain_controllers'] | default([])
    - autonomy_ownca_objectguid is truthy

- name: "Set extended key usage based on role."
  ansible.builtin.set_fact:
    autonomy_ownca_host_extended_key_usage: "{{ autonomy_ownca_host_extended_key_usage + [item.extended_key_uasge] }}"
  loop:
    - name: "samba_domain_controllers"
      extended_key_uasge: "{{ autonomy_ownca_mskdc_oid }}"
  become: false
  when:
    - inventory_hostname in groups[item.name] | default([])

- name: "Setup OwnCA: Definitions."
  ansible.builtin.include_tasks: "ca_definitions.yml"

- name: "Get Component CA Cert information."
  community.crypto.x509_certificate_info:
    path: "{{ autonomy_ownca_componentca_cert_path }}"
  register: __autonomy_ownca_componentca_cert_info
  delegate_to: "{{ autonomy_ownca_certificate_authority_host }}"
  become: false

- name: "Include OS Family Preparation Tasks."
  ansible.builtin.include_tasks: "host_{{ ansible_os_family | lower }}_prep.yml"
  when:
    - ansible_network_os is not defined
    - ansible_os_family is defined
    - not autonomy_ownca_generate_locally
    - inventory_hostname not in groups["vendor_managed"]

- name: "Include Localhost Preparation Tasks."
  ansible.builtin.include_tasks: "host_localhost_prep.yml"
  when:
    - ansible_network_os is defined or autonomy_ownca_generate_locally or inventory_hostname in groups["vendor_managed"]

# # ==================================================================================================
# #
# # The next four tasks ensure we regenerate the host certificate if the issuing certificate is newer
# # than the host certificate.
# #
# # ==================================================================================================
# - name: "Check if host cert exists."
#   ansible.builtin.stat:
#     path: "{{ ownca_hosts_directory }}/certs/{{ inventory_hostname }}.crt"
#   delegate_to: localhost
#   become: false
#   register: cert_file
#   when:
#     - inventory_hostname not in groups["vendor_managed"] or ownca_generate_locally or ansible_network_os is defined

# - name: "Get host certificate information."
#   community.crypto.x509_certificate_info:
#     path: "{{ cert_file.stat.path }}"
#   become: false
#   delegate_to: localhost
#   register: host_cert
#   when:
#     - cert_file.stat is defined
#     - cert_file.stat.exists is true
#     - cert_file.stat.path is defined

# # ==================================================================================================
# #
# # We want to check if these match, because if they don't we need to force regeneration of the host's
# # certificate.  A mismatch typically happens when the issuing CA's cert has been updated while the
# # host's certificate has not.
# #
# # ==================================================================================================
# - name: "Check if we are regenerating host certs."
#   ansible.builtin.set_fact:
#     __host_cert_force_regeneration: true
#   become: false
#   changed_when: __host_cert_force_regeneration
#   tags:
#     - never
#     - regenerate-host-certs

# - name: "Check if the host's cert authority_key_identifier matches the Component CA's subject_key_identifier."
#   ansible.builtin.set_fact:
#     __host_cert_force_regeneration: true
#   become: false
#   when:
#     - host_cert.authority_key_identifier is defined
#     - host_cert.authority_key_identifier != component_cert.subject_key_identifier

- name: "Generate Host Certificate." # noqa: jinja[spacing]
  community.crypto.x509_certificate:
    path: "{{ autonomy_ownca_hosts_cert_path }}"
    csr_path: "{{ autonomy_ownca_hosts_csr_path }}"
    ownca_path: "{{ autonomy_ownca_componentca_cert_path }}"
    ownca_privatekey_path: "{{ autonomy_ownca_componentca_key_path }}"
    ownca_privatekey_passphrase: "{{ __password }}"
    provider: ownca
    owner: "{{ autonomy_ownca_user }}"
    group: "{{ autonomy_ownca_group }}"
    mode: "{{ autonomy_ownca_hosts_cert_mode }}"
    backup: "{{ autonomy_ownca_host_cert_backup }}"
    # force: "{{ __host_cert_force_regeneration }}"
  become: false
  delegate_to: "{{ autonomy_ownca_certificate_authority_host }}"
  vars:
    __password: >-
      {% if autonomy_ownca_componentca_password == "password" -%}
      {{ lookup('community.general.passwordstore', autonomy_ownca_componentca_password_store_lookup) }}
      {%- else -%}
      {{ autonomy_ownca_componentca_password }}
      {%- endif %}

- name: "Identify Certificate Complete Chain."
  community.crypto.certificate_complete_chain:
    input_chain: "{{ lookup('file', autonomy_ownca_hosts_cert_path) }}"
    intermediate_certificates:
      - "{{ autonomy_ownca_componentca_cert_path }}"
      - "{{ autonomy_ownca_intermediateca_cert_path }}"
    root_certificates:
      - "{{ autonomy_ownca_rootca_cert_path }}"
  register: parent_cert_authorities
  become: false
  delegate_to: "{{ autonomy_ownca_certificate_authority_host }}"

# ==================================================================================================
#
# TODO: Need to identify if the chain has actually changed before writing the new chain file.
#
# ==================================================================================================
- name: "Write complete chain to disk."
  ansible.builtin.copy:
    dest: "{{ autonomy_ownca_hosts_chain_path }}"
    content: "{{ ''.join(parent_cert_authorities.complete_chain) }}"
    owner: "{{ autonomy_ownca_user }}"
    group: "{{ autonomy_ownca_group }}"
    mode: "{{ autonomy_ownca_hosts_chain_mode }}"
  become: false
  delegate_to: "{{ autonomy_ownca_certificate_authority_host }}"
  when:
    - parent_cert_authorities.complete_chain is defined

- name: "Include OS Family Finalization Tasks."
  ansible.builtin.include_tasks: "host_{{ ansible_os_family | lower }}_final.yml"
  when:
    - ansible_network_os is not defined
    - ansible_os_family is defined
    - not autonomy_ownca_generate_locally
    - inventory_hostname not in groups["vendor_managed"]

# - name: "Include NetworkOS Tasks."
#   ansible.builtin.include_tasks: "hosts_{{ ansible_network_os.split('.')[2] | lower }}_final.yml"
#   when:
#     - ansible_network_os is defined
#     - not ownca_generate_locally

# - name: "Include Local tasks."
#   ansible.builtin.include_tasks: "hosts_localhost_final.yml"
#   when:
#     - ownca_generate_locally
#     - inventory_hostname in groups["vendor_managed"]

# - name: "Copy to Samba File Server."
#   ansible.builtin.include_tasks: "copy_to_samba.yml"
#   when:
#     - inventory_hostname == groups['samba_ownca_user_hosts'][0] | default([])

#  LocalWords:  componentca
