---
- name: "Install packages"
  ansible.builtin.package:
    name: "{{ autonomy_systemd_networkd_packages }}"
    state: present
  become: true
  notify: "restart systemd-networkd"
  tags:
    - systemd
    - systemd-networkd

- name: "Install Netdev Files."
  ansible.builtin.template:
    src: "etc/systemd/network/netdev.j2"
    dest: "/etc/systemd/network/{{ item.id }}-{{ item.name }}.netdev"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ autonomy_systemd_netdev }}"
  become: true
  notify: "restart systemd-networkd"
  when:
    - autonomy_systemd_netdev is defined
  tags:
    - systemd
    - systemd-networkd

- name: "Install Network Files."
  ansible.builtin.template:
    src: "etc/systemd/network/network.j2"
    dest: "/etc/systemd/network/{{ item.id }}-{{ item.name }}.network"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ autonomy_systemd_network }}"
  become: true
  notify: "restart systemd-networkd"
  when:
    - autonomy_systemd_network is defined
  tags:
    - systemd
    - systemd-networkd

# ==================================================================================================
#
# FIXME: ignore-errors ansible-lint.
#
# This fails if the service doesn't exist.  For example, if distribution changing the service name,
# and the old one is still listed.
#
# This is fine since I want it disabled if it does exist.
#
# ==================================================================================================
- name: "Disable old networking services."
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    masked: true
  loop: "{{ autonomy_systemd_old_networking_services }}"
  become: true
  when: (autonomy_systemd_netdev is defined) or (autonomy_systemd_network is defined)
  ignore_errors: true # noqa: ignore-errors
  tags:
    - systemd
    - systemd-networkd

- name: "Enable Systemd-Networkd"
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
  loop:
    - systemd-networkd
    - systemd-resolved
  become: true
  when: (autonomy_systemd_netdev is defined) or (autonomy_systemd_network is defined)
  tags:
    - systemd
    - systemd-networkd

# ==================================================================================================
#
# This last section cleans up anything leftover from old networking config.
#
# ==================================================================================================
- name: "Run tasks for: {{ ansible_os_family }}"
  ansible.builtin.include_tasks: "networkd_{{ ansible_os_family | lower }}.yml"

- name: "Remove unnecessary folders."
  ansible.builtin.file:
    path: "/etc/{{ item }}"
    state: absent
  loop:
    - NetworkManager
    - network
    - dhcp
    - avahi
  become: true
  tags:
    - systemd
    - systemd-networkd

#  LocalWords:  networkd
