# ==================================================================================================
#
# Test Kerberos
#
# ==================================================================================================
- name: "Test Kerberos Logon to Active Directory Domain Controller."
  ansible.builtin.expect:
    command: kinit administrator
    responses:
      (?i)password: "{{ samba_administrator_password }}"
  no_log: true
  become: false
  when:
    - inventory_hostname != __samba_schema_master

- name: "Test Kerberos Ticket from Active Directory Domain Controller"
  ansible.builtin.command:
    cmd: "klist"
  register: success
  become: false
  when:
    - inventory_hostname != __samba_schema_master
