---
- name: "Install packages."
  ansible.builtin.package:
    name: "{{ autonomy_sshca_host_certs_packages }}"
    state: present
  become: true
  tags:
    - sshca
    - sshca-host-certs
    - install-packages

- name: "Create persistant host certificate directory."
  ansible.builtin.file:
    path: "{{ autonomy_sshca_host_dir }}/{{ inventory_hostname }}"
    owner: "{{ autonomy_common_user }}"
    group: "{{ autonomy_common_group }}"
    mode: "0755"
    state: directory
  become: false
  delegate_to: localhost
  tags:
    - sshca
    - sshca-host-certs

- name: "Fetch public keys."
  ansible.builtin.fetch:
    src: "{{ autonomy_common_openssh_host_pub_path }}"
    dest: "{{ autonomy_sshca_host_pub_path }}"
    flat: true
  changed_when: false
  become: true
  tags:
    - sshca
    - sshca-host-certs

# ==================================================================================================
#
# Sign SSH Keys
#
# TODO: Add serial number
#
# Set 'use_agent' to true, to enable use of passwords for signing keys.
#
# ==================================================================================================
- name: "Sign SSH Public Keys."
  community.crypto.openssh_cert:
    signing_key: "{{ autonomy_sshca_hostca_key_path }}"
    public_key: "{{ autonomy_sshca_host_pub_path }}"
    path: "{{ autonomy_sshca_host_cert_path }}"
    identifier: "{{ autonomy_sshca_hostca_key_comment }}"
    type: "host"
    principals: "{{ autonomy_sshca_host_principals }}"
    #serial_number:
    valid_at: "{{ autonomy_sshca_host_valid_at }}"
    valid_from: "{{ autonomy_sshca_host_valid_from }}"
    valid_to: "{{ autonomy_sshca_host_valid_to }}"
    ignore_timestamps: "{{ autonomy_sshca_host_ignore_timestamps }}"
    use_agent: "{{ autonomy_sshca_use_agent }}"
    regenerate: "{{ autonomy_sshca_host_regenerate }}"
    force: "{{ autonomy_sshca_host_force }}"
    owner: "{{ autonomy_common_user }}"
    group: "{{ autonomy_common_group }}"
    mode: "0644"
    state: "present"
  delegate_to: localhost
  become: false
  tags:
    - sshca
    - sshca-host-certs

- name: "Create Required Directories for Cert authorization."
  ansible.builtin.file:
    name: "{{ autonomy_common_openssh_ca_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  tags:
    - sshca
    - sshca-host-certs

- name: "Copy CA Public Keys to Server."
  ansible.builtin.copy:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ autonomy_sshca_ca_public_keys }}"
  notify: restart ssh
  become: true
  tags:
    - sshca
    - sshca-host-certs

- name: "Copy Host Certificates to Server."
  ansible.builtin.copy:
    src: "{{ autonomy_sshca_host_cert_path }}"
    dest: "{{ autonomy_common_openssh_host_cert_path }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart ssh
  become: true
  tags:
    - sshca
    - sshca-host-certs
