---
# tasks file for sshca-user-certs
- name: "Create persistant host certificate directory."
  ansible.builtin.file:
    path: "{{ autonomy_sshca_user_dir }}/{{ inventory_hostname }}"
    owner: "{{ autonomy_common_user }}"
    group: "{{ autonomy_common_group }}"
    mode: "0755"
    state: directory
  become: false
  delegate_to: localhost
  tags:
    - sshca
    - sshca-user-certs

- name: "Fetch user SSH public keys."
  ansible.builtin.fetch:
    src: "{{ item['unix_home'] }}/.ssh/id_{{ item['ssh_key_type'] }}.pub"
    dest: "{{ autonomy_sshca_user_dir }}/{{ inventory_hostname }}/{{ item['username'] }}.pub"
    flat: true
  loop: "{{ autonomy_sshca_users }}"
  changed_when: false
  become: true
  when:
    - item['id_number'] is defined

- name: "Sign SSH Public Keys (Non RSA CA Key)."
  community.crypto.openssh_cert:
    signing_key: "{{ autonomy_sshca_userca_key_path }}"
    public_key: "{{ autonomy_sshca_user_dir }}/{{ inventory_hostname }}/{{ item['username'] }}.pub"
    path: "{{ autonomy_sshca_user_dir }}/{{ inventory_hostname }}/{{ item['username'] }}-cert.pub"
    identifier: "{{ item['mail'] | default(__mail) }}"
    type: "user"
    principals: "{{ item['ssh_principals'] | default(None) }}"
    #serial_number:
    valid_at: "{{ autonomy_sshca_user_valid_at }}"
    valid_from: "{{ autonomy_sshca_user_valid_from }}"
    valid_to: "{{ autonomy_sshca_user_valid_to }}"
    owner: "{{ autonomy_common_user }}"
    group: "{{ autonomy_common_group }}"
    mode: "0600"
    #ignore_timestamps: "{{ autonomy_sshca_user_ignore_timestamps }}"
    regenerate: "{{ autonomy_sshca_user_regenerate }}"
    state: "present"
    force: "{{ autonomy_sshca_user_force }}"
    use_agent: "{{ autonomy_sshca_user_use_agent }}"
  loop: "{{ autonomy_sshca_users }}"
  delegate_to: localhost
  become: false
  vars:
    __mail: "{{ item['username'] }}@{{ inventory_hostname }}"
  when:
    - autonomy_sshca_userca_key_type != "rsa"
    - item['id_number'] is defined

- name: "Sign SSH Public Keys (RSA CA Key)."
  community.crypto.openssh_cert:
    signing_key: "{{ autonomy_sshca_userca_key_path }}"
    public_key: "{{ autonomy_sshca_user_dir }}/{{ inventory_hostname }}/{{ item['username'] }}.pub"
    path: "{{ autonomy_sshca_user_dir }}/{{ inventory_hostname }}/{{ item['username'] }}-cert.pub"
    identifier: "{{ item['mail'] | default(__mail) }}"
    type: "user"
    principals: "{{ item['ssh_principals'] | default(None) }}"
    signature_algorithm: "{{ autonomy_sshca_userca_signature_algorithm }}"
    #serial_number:
    valid_at: "{{ autonomy_sshca_user_valid_at }}"
    valid_from: "{{ autonomy_sshca_user_valid_from }}"
    valid_to: "{{ autonomy_sshca_user_valid_to }}"
    owner: "{{ autonomy_common_user }}"
    group: "{{ autonomy_common_group }}"
    mode: "0600"
    #ignore_timestamps: "{{ autonomy_sshca_user_ignore_timestamps }}"
    regenerate: "{{ autonomy_sshca_user_regenerate }}"
    state: "present"
    force: "{{ autonomy_sshca_user_force }}"
    use_agent: "{{ autonomy_sshca_user_use_agent }}"
  loop: "{{ autonomy_sshca_users }}"
  delegate_to: localhost
  become: false
  vars:
    __mail: "{{ item['username'] }}@{{ inventory_hostname }}"
  when:
    - autonomy_sshca_userca_key_type == "rsa"
    - item['id_number'] is defined

- name: "Install SSH Certificate."
  ansible.builtin.copy:
    src: "{{ autonomy_sshca_user_dir }}/{{ inventory_hostname }}/{{ item['username'] }}-cert.pub"
    dest: "{{ item['unix_home'] }}/.ssh/id_{{ item['ssh_key_type'] }}-cert.pub"
    owner: "{{ item['id_number'] }}"
    group: "{{ item['id_number'] }}"
    mode: "0644"
    #backup: true
  loop: "{{ autonomy_sshca_users }}"
  become: true
  when:
    - item['id_number'] is defined
    - item['ssh_principals'] is defined and item['ssh_principals'] is truthy

# - name: "Create SSH Principals file for users."
#   ansible.builtin.template:
#     src: "ssh_principals.j2"
#     dest: "/etc/ssh/auth_principals/{{ __realm }}{{ item.username }}"
#     owner: root
#     group: root
#     mode: '0644'
#   loop: "{{ autonomy_sshca_users }}"
#   become: true
#   when:
#     - item['id_number'] is defined
