---
- name: "Install packages."
  ansible.builtin.package:
    name: "{{ autonomy_sshca_packages }}"
    state: present
  become: true
  delegate_to: localhost
  run_once: true
  tags:
    - sshca
    - install-packages

- name: "Create CA key directory."
  ansible.builtin.file:
    path: "{{ autonomy_sshca_ca_dir }}"
    state: directory
    owner: "{{ autonomy_sshca_user }}"
    group: "{{ autonomy_sshca_group }}"
    mode: '0700'
  run_once: true
  delegate_to: localhost
  become: false
  tags:
    - sshca

# ==================================================================================================
#
# Generate Passwords if they don't exist
#
# ==================================================================================================
- name: "Ensure we have a password for the Host CA Key."
  ansible.builtin.set_fact:
    autonomy_sshca_hostca_key_password: "{{ lookup('community.general.passwordstore', __password_lookup) }}"
  vars:
    __password_store_id: "{{ autonomy_common_password_db }}/{{ autonomy_common_root_domain }}/sshca/sshca_host_key_password"
    __password_length: "length={{ autonomy_common_password_length }}"
    __password_overwrite: "overwrite={{ autonomy_common_password_overwrite }} backup=yes"
    __password_create: "create=true"
    __password_symbols: "nosymbols={{ autonomy_common_password_no_symbols }}"
    __password_lookup: "{{ __password_store_id }} {{ __password_create }} {{ __password_length }} {{ __password_symbols }} {{ __password_overwrite }}"
  run_once: true
  delegate_to: localhost
  become: false
  no_log: true
  changed_when:
    - autonomy_sshca_hostca_key_password != "password"
  when:
    - autonomy_sshca_hostca_key_password == "password"
  tags:
    - sshca
    - sshca_debug
    - sshca-debug

- name: "Ensure we have a password for the User CA Key."
  ansible.builtin.set_fact:
    autonomy_sshca_userca_key_password: "{{ lookup('community.general.passwordstore', __password_lookup) }}"
  vars:
    __password_store_id: "{{ autonomy_common_password_db }}/{{ autonomy_common_root_domain }}/sshca/sshca_user_key_password"
    __password_length: "length={{ autonomy_common_password_length }}"
    __password_overwrite: "overwrite={{ autonomy_common_password_overwrite }} backup=yes"
    __password_create: "create=true"
    __password_symbols: "nosymbols={{ autonomy_common_password_no_symbols }}"
    __password_lookup: "{{ __password_store_id }} {{ __password_create }} {{ __password_length }} {{ __password_symbols }} {{ __password_overwrite }}"
  delegate_to: localhost
  become: false
  no_log: true
  changed_when:
    - autonomy_sshca_userca_key_password != "password"
  when:
    - autonomy_sshca_userca_key_password == "password"
  tags:
    - sshca
    - sshca_debug
    - sshca-debug

# ==================================================================================================
#
# Generate CA keys
#
# ==================================================================================================
- name: "Generate Host CA keys."
  community.crypto.openssh_keypair:
    path: "{{ autonomy_sshca_hostca_key_path }}"
    type: "{{ autonomy_sshca_hostca_key_type }}"
    comment: "{{ autonomy_sshca_hostca_key_comment }}"
    passphrase: "{{ autonomy_sshca_hostca_key_password }}"
    owner: "{{ autonomy_sshca_user }}"
    group: "{{ autonomy_sshca_group }}"
    mode: "0600"
    state: "present"
    regenerate: "full_idempotence"
    force: false
  become: false

- name: "Generate User CA keys."
  community.crypto.openssh_keypair:
    path: "{{ autonomy_sshca_userca_key_path }}"
    type: "{{ autonomy_sshca_userca_key_type }}"
    comment: "{{ autonomy_sshca_userca_key_comment }}"
    passphrase: "{{ autonomy_sshca_userca_key_password }}"
    owner: "{{ autonomy_sshca_user }}"
    group: "{{ autonomy_sshca_group }}"
    state: "present"
    regenerate: "full_idempotence"
    mode: "0600"
    force: false
  become: false
