---
# tasks file for etc_crontab
- name: Include OS-specific variables.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ autonomy_cron_packages }}"
    state: present
  become: true

- name: "Install Configuration files"
  ansible.builtin.template:
    src: "etc/crontab.j2"
    dest: "{{ autonomy_cron_path }}"
    owner: root
    group: root
    mode: "0644"
    backup: "{{ 'false' if autonomy_common_etckeeper_enabled else 'true' }}"
  become: true
