---
# ==================================================================================================
#
# DNS Settings
#
# ==================================================================================================
autonomy_maintenance_dns_url_data_dir: "{{ autonomy_common_user_dir }}/.ansible/data"

# Records
autonomy_maintenance_dns_spf_mail_servers: ""
autonomy_maintenance_dns_spf_record_includes: []
autonomy_maintenance_dns_spf_record_fail: "-all"

# Dmarc
autonomy_maintenance_dns_dmarc_policy: "reject"
autonomy_maintenance_dns_dmarc_percent: 100
autonomy_maintenance_dns_dmarc_local_email: "dmarc@{{ inventory_hostname }}"
autonomy_maintenance_dns_dmarc_aspf: "s" # 's' for strict, 'r' for relaxed
autonomy_maintenance_dns_dmarc_adkim: "s" # 's' for strict, 'r' for relaxed

autonomy_maintenance_dns_dmarc_email:
  - "{{ autonomy_maintenance_dns_dmarc_local_email }}"
  # - "{{ autonomy_maintenance_cloudflare_dmarc_email }}"

autonomy_maintenance_dns_dmarc_record: '"v=DMARC1; p={{ autonomy_maintenance_dns_dmarc_policy }}; {{ __autonomy_maintenance_dns_dmarc_percent }}{{ __autonomy_maintenance_dns_dmarc_email }}; adkim={{ autonomy_maintenance_dns_dmarc_adkim }}; aspf={{ autonomy_maintenance_dns_dmarc_aspf }}"'
autonomy_maintenance_dns_spf_record: '"v=spf1 {{ __autonomy_maintenance_dns_spf_includes }} {{ autonomy_maintenance_dns_spf_record_fail }}"'


__autonomy_maintenance_dns_dmarc_percent: "{% if autonomy_maintenance_dns_dmarc_percent != 100 %}pct={{ autonomy_maintenance_dns_dmarc_percent }}; {% endif %}"
__autonomy_maintenance_dns_dmarc_email: "rua={% for email in autonomy_maintenance_dns_dmarc_email %}mailto:{{ email }}{{ ',' if not loop.last else '' }}{% endfor %}"

__autonomy_maintenance_dns_spf_includes: "{% for server in autonomy_maintenance_dns_spf_record_includes %}include:{{ server }}{{ ' ' if not loop.last else '' }}{% endfor %}"

#  LocalWords:  adkim
