---
# tasks file for acmeca_challenge_site
- name: "Include OS-specific variables."
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false
  tags:
    - acmeca
    - acmeca-test
    - acmeca-account
    - acmeca-certs
    - acmeca-http
    - acmeca-dns

- name: "Install packages."
  ansible.builtin.package:
    name: "{{ autonomy_acmeca_packages }}"
    state: present
  become: true
  tags:
    - acmeca
    - acmeca-test
    - acmeca-account
    - acmeca-certs
    - acmeca-http
    - acmeca-dns

- name: "Configure Account Tasks."
  ansible.builtin.include_tasks: "config.yml"
  tags:
    - acmeca
    - acmeca-account
    - acmeca-test

- name: "Run ACME Account Tasks."
  ansible.builtin.include_tasks: "account.yml"
  when:
    __acmeca_tasks == "account"
  tags:
    - acmeca
    - acmeca-account
    - acmeca-test

- name: "Create Certificate."
  ansible.builtin.include_tasks: "cert.yml"
  when:
    __acmeca_tasks == "certs"
  tags:
    - acmeca
    - acmeca-test
    - acmeca-certs
