---
# ======================================================================
#
# Tasks:
#
#
# ======================================================================
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false
  tags:
    - openssh
    - install-packages

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ autonomy_openssh_packages }}"
    state: present
  become: true
  tags:
    - openssh
    - install-packages

- name: "Create Required Directories for Cert authorization."
  ansible.builtin.file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  loop:
    - "{{ autonomy_common_openssh_ca_dir }}"
    - "{{ autonomy_common_openssh_authorized_principals_dir }}"
  tags:
    - openssh

# ==================================================================================================
#
# This variable is needed for generating /etc/ssh/ssh_known_hosts
#
# ==================================================================================================
- name: "Get Host CA public key"
  ansible.builtin.set_fact:
    __openssh_host_ca_public_key: "{{ lookup('file', autonomy_common_sshca_hostca_openssh_pub_path) }}"
  delegate_to: localhost
  run_once: true
  become: false
  tags:
    - openssh

- name: "Install Configuration files"
  ansible.builtin.template:
    src: "etc/ssh/{{ item['name'] }}.j2"
    dest: "{{ item['path'] }}"
    owner: root
    group: root
    mode: "{{ item['mode'] | default('0644') }}"
    validate: "{{ item['validate'] | default(none) }}"
    backup: "{{ 'false' if autonomy_common_etckeeper_enabled else 'true' }}"
  become: true
  loop: "{{ autonomy_openssh_config_files }}"
  notify: restart ssh
  tags:
    - openssh

- name: "Install ssh_config.d files."
  ansible.builtin.template:
    src: "etc/ssh/ssh_config.d/conf.j2"
    dest: "{{ item['path'] }}"
    owner: "root"
    group: "root"
    mode: "{{ item['mode'] | default('0644') }}"
    backup: "{{ 'false' if autonomy_common_etckeeper_enabled else 'true' }}"
  become: true
  loop: "{{ autonomy_openssh_ssh_conf_d }}"
  notify: restart ssh
  when:
    - item['enabled']
  tags:
    - openssh

- name: "Remove ssh_config.d files."
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: "absent"
  become: true
  loop: "{{ autonomy_openssh_ssh_conf_d }}"
  notify: restart ssh
  when:
    - not item['enabled']
  tags:
    - openssh
