---
autonomy_etckeeper_packages:
  - "{{ autonomy_common_etckeeper_package }}"

autonomy_etckeeper_conf_dir: "{{ autonomy_common_sysconf_dir }}/etckeeper"
autonomy_etckeeper_conf_file: "etckeeper.conf"
autonomy_etckeeper_conf_path: "{{ autonomy_etckeeper_conf_dir }}/{{ autonomy_etckeeper_conf_file }}"

# These variables must be explicitly set.
autonomy_etckeeper_vcs: "git"
autonomy_etckeeper_highlevel_package_manager: "apt"
autonomy_etckeeper_lowlevel_package_manager: "dpkg"

# The following variables match their defaults
autonomy_etckeeper_git_commit_options: ""
autonomy_etckeeper_hg_commit_options: ""
autonomy_etckeeper_bzr_commit_options: ""
autonomy_etckeeper_darcs_commit_options: "-a"
autonomy_etckeeper_avoid_daily_autocommits: "{{ __autonomy_etckeeper_avoid_daily_autocommits }}"
autonomy_etckeeper_avoid_special_file_warning: "{{ __autonomy_etckeeper_avoid_special_file_warning }}"
autonomy_etckeeper_avoid_commit_before_install: "{{ __autonomy_etckeeper_avoid_commit_before_install }}"
autonomy_etckeeper_push_remote: ""

# ==================================================================================================
#
# Do NOT Use these variables.  They are used to track internal application defaults.
#
# ==================================================================================================
__autonomy_etckeeper_git_commit_options: ""
__autonomy_etckeeper_hg_commit_options: ""
__autonomy_etckeeper_bzr_commit_options: ""
__autonomy_etckeeper_avoid_daily_autocommits: "0"
__autonomy_etckeeper_avoid_special_file_warning: "0"
__autonomy_etckeeper_avoid_commit_before_install: "0"
