---
# tasks file for aliases
- name: "Ensure we have users required by host role."
  ansible.builtin.set_fact:
    autonomy_users: "{{ autonomy_users + [item['user']] }}"
  loop:
    - name: "mythtv"
      user: "{{ user_mythtv }}"
    - name: "file_servers"
      user: "{{ user_mythtv }}"
    - name: "file_servers"
      user: "{{ user_git }}"
    - name: "minidlna_servers"
      user: "{{ user_minidlna }}"
    - name: "git_servers"
      user: "{{ user_git }}"
    - name: "homeassistant"
      user: "{{ user_homeassistant }}"
    - name: "mail_servers"
      user: "{{ user_vmail }}"
  become: false
  when:
    - inventory_hostname in groups[item.name] | default([])

- name: "Install /etc configuration files."
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - aliases
  become: true
  when:
    - autonomy_users is defined
