---
# ==================================================================================================
#
# Task: "Set Hostname"
#
# Allows changing a hostname simply by updating the hosts IP address
#
# ==================================================================================================
- name: "Set Hostname"
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: true
  when:
    - inventory_hostname != "localhost"
  tags:
    - hostname
