---
# tasks file for etc_mailname
- name: "Install /etc configuration files."
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  become: true
  loop:
    - mailname
