---
# tasks file for etc
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false
  tags:
    - aliases
    - fstab
    - hostname
    - hosts
    - skel
    - timezone

- name: "Include Aliases tasks."
  ansible.builtin.include_tasks: "aliases.yml"
  when:
    - __etc_tasks == "aliases"
  tags:
    - aliases

- name: "Include Fstab Tasks."
  ansible.builtin.include_tasks: "fstab.yml"
  when:
    - __etc_tasks == "fstab"
  tags:
    - fstab

- name: "Include Hostname Tasks."
  ansible.builtin.include_tasks: "hostname.yml"
  when:
    - __etc_tasks == "hostname"
  tags:
    - hostname

- name: "Include Hosts Tasks."
  ansible.builtin.include_tasks: "hosts.yml"
  when:
    - __etc_tasks == "hosts"
  tags:
    - hosts

- name: "Include Skel file tasks."
  ansible.builtin.include_tasks: "skel.yml"
  when:
    - __etc_tasks == "skel"
  tags:
    - skel

- name: "Include Timezone Tasks."
  ansible.builtin.include_tasks: "timezone.yml"
  when:
    - __etc_tasks == "timezone"
  tags:
    - timezone
