---
autonomy_ownca_issuingcas:
  - common_name: "{{ autonomy_ownca_componentca_common_name }}"
    key_path: "{{ autonomy_ownca_componentca_key_path }}"
    csr_path: "{{ autonomy_ownca_componentca_csr_path }}"
    cert_path: "{{ autonomy_ownca_componentca_cert_path }}"
    password: "{{ autonomy_ownca_componentca_password }}"
    password_lookup: "{{ autonomy_ownca_componentca_password_store_lookup }}"
    org_name: "{{ autonomy_ownca_componentca_org_name }}"
    org_unit_name: "{{ autonomy_ownca_componentca_org_unit_name }}"
    country_code: ""
    country_name: ""
    region_name: ""
    email_address: ""
    keyusage: "{{ autonomy_ownca_componentca_keyusage }}"
    keyusage_critical: "{{ autonomy_ownca_intermediateca_keyusage_critical }}"
    basic_constraints: "{{ autonomy_ownca_intermediateca_basic_constraints }}"
    basic_constraints_critical: "{{ autonomy_ownca_componentca_basic_constraints_critical }}"
    create_subject_key_id: "{{ autonomy_ownca_intermediateca_create_subject_key_identifier }}"
    crl_url: "{{ autonomy_ownca_componentca_crl_distribution_point_url }}"
    crl_reasons: "{{ autonomy_ownca_componentca_crl_distribution_points_reasons }}"
  - common_name: "{{ autonomy_ownca_identityca_common_name }}"
    key_path: "{{ autonomy_ownca_identityca_key_path }}"
    csr_path: "{{ autonomy_ownca_identityca_csr_path }}"
    cert_path: "{{ autonomy_ownca_identityca_cert_path }}"
    password: "{{ autonomy_ownca_identityca_password }}"
    password_lookup: "{{ autonomy_ownca_identityca_password_store_lookup }}"
    org_name: "{{ autonomy_ownca_identityca_org_name }}"
    org_unit_name: "{{ autonomy_ownca_identityca_org_unit_name }}"
    country_code: ""
    country_name: ""
    region_name: ""
    email_address: ""
    keyusage: "{{ autonomy_ownca_identityca_keyusage }}"
    keyusage_critical: "{{ autonomy_ownca_intermediateca_keyusage_critical }}"
    basic_constraints: "{{ autonomy_ownca_intermediateca_basic_constraints }}"
    basic_constraints_critical: "{{ autonomy_ownca_identityca_basic_constraints_critical }}"
    create_subject_key_id: "{{ autonomy_ownca_intermediateca_create_subject_key_identifier }}"
    crl_url: "{{ autonomy_ownca_identityca_crl_distribution_point_url }}"
    crl_reasons: "{{ autonomy_ownca_identityca_crl_distribution_points_reasons }}"
  - common_name: "{{ autonomy_ownca_codesignca_common_name }}"
    key_path: "{{ autonomy_ownca_codesignca_key_path }}"
    csr_path: "{{ autonomy_ownca_codesignca_csr_path }}"
    cert_path: "{{ autonomy_ownca_codesignca_cert_path }}"
    password: "{{ autonomy_ownca_codesignca_password }}"
    password_lookup: "{{ autonomy_ownca_codesignca_password_store_lookup }}"
    org_name: "{{ autonomy_ownca_codesignca_org_name }}"
    org_unit_name: "{{ autonomy_ownca_codesignca_org_unit_name }}"
    country_code: ""
    country_name: ""
    region_name: ""
    email_address: ""
    keyusage: "{{ autonomy_ownca_codesignca_keyusage }}"
    keyusage_critical: "{{ autonomy_ownca_intermediateca_keyusage_critical }}"
    basic_constraints: "{{ autonomy_ownca_intermediateca_basic_constraints }}"
    basic_constraints_critical: "{{ autonomy_ownca_codesignca_basic_constraints_critical }}"
    create_subject_key_id: "{{ autonomy_ownca_intermediateca_create_subject_key_identifier }}"
    crl_url: "{{ autonomy_ownca_codesignca_crl_distribution_point_url }}"
    crl_reasons: "{{ autonomy_ownca_codesignca_crl_distribution_points_reasons }}"
