---
# tasks file for etckeeper
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false
  tags:
    - etckeeper
    - install-packages

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ autonomy_etckeeper_packages }}"
    state: present
  become: true
  tags:
    - etckeeper
    - install-packages

  # NOTE: We do not back this up because etckeeper allows git to manage backups.
- name: "Install etckeeper configuration file."
  ansible.builtin.template:
    src: "etc/etckeeper/etckeeper.conf.j2"
    dest: "{{ autonomy_etckeeper_conf_path }}"
    owner: root
    group: root
    mode: "0644"
    backup: false
  become: true
  notify:
    - "restart {{ autonomy_common_etckeeper_daemon }}"
  tags:
    - etckeeper
