---
autonomy_common_dns_rpz_enabled: false
autonomy_common_dns_rpz_primary_nameservers: []
autonomy_common_dns_rpz_zone_type: "{{ autonomy_common_bind_primary_zone }}"
autonomy_common_dns_rpz_default_policy: "given"
autonomy_common_dns_rpz_dir: "{{ autonomy_common_bind_cache_dir }}"
autonomy_common_dns_rpz_also_notify: []

# Allow List
autonomy_common_dns_rpz_allowlist_name: "allowlist"
autonomy_common_dns_rpz_allowlist_policy: "{{ autonomy_common_dns_rpz_default_policy }}"
autonomy_common_dns_rpz_allowlist_zone_file: "db.{{ autonomy_common_dns_rpz_allowlist_name }}.rpz"
autonomy_common_dns_rpz_allowlist_zone_path: "{{ autonomy_common_dns_rpz_dir }}/{{ autonomy_common_dns_rpz_allowlist_zone_file }}"
autonomy_common_dns_rpz_allowlist_allow_query: "{{ autonomy_common_bind_allow_query }}"
autonomy_common_dns_rpz_allowlist_zone_type: "{{ autonomy_common_dns_rpz_zone_type }}"
autonomy_common_dns_rpz_allowlist_nameservers: "{{ autonomy_common_dns_rpz_primary_nameservers }}"
autonomy_common_dns_rpz_allowlist_also_notify: "{{ autonomy_common_dns_rpz_also_notify }}"
autonomy_dns_allowlist_records_present: []
autonomy_dns_allowlist_records_absent: []

# Redirect List
autonomy_common_dns_rpz_redirectlist_name: "redirectlist"
autonomy_common_dns_rpz_redirectlist_policy: "{{ autonomy_common_dns_rpz_default_policy }}"
autonomy_common_dns_rpz_redirectlist_zone_file: "db.{{ autonomy_common_dns_rpz_redirectlist_name }}.rpz"
autonomy_common_dns_rpz_redirectlist_zone_path: "{{ autonomy_common_dns_rpz_dir }}/{{ autonomy_common_dns_rpz_redirectlist_zone_file }}"
autonomy_common_dns_rpz_redirectlist_allow_query: "{{ autonomy_common_bind_allow_query }}"
autonomy_common_dns_rpz_redirectlist_zone_type: "{{ autonomy_common_dns_rpz_zone_type }}"
autonomy_common_dns_rpz_redirectlist_nameservers: "{{ autonomy_common_dns_rpz_primary_nameservers }}"
autonomy_common_dns_rpz_redirectlist_also_notify: "{{ autonomy_common_dns_rpz_also_notify }}"
autonomy_dns_redirectlist_records_present: []
autonomy_dns_redirectlist_records_absent: []

# Blocklist
autonomy_common_dns_rpz_blocklist_name: "blocklist"
autonomy_common_dns_rpz_blocklist_policy: "{{ autonomy_common_dns_rpz_default_policy }}"
autonomy_common_dns_rpz_blocklist_zone_file: "db.{{ autonomy_common_dns_rpz_blocklist_name }}.rpz"
autonomy_common_dns_rpz_blocklist_zone_path: "{{ autonomy_common_dns_rpz_dir }}/{{ autonomy_common_dns_rpz_blocklist_zone_file }}"
autonomy_common_dns_rpz_blocklist_allow_query: "{{ autonomy_common_bind_allow_query }}"
autonomy_common_dns_rpz_blocklist_zone_type: "{{ autonomy_common_dns_rpz_zone_type }}"
autonomy_common_dns_rpz_blocklist_nameservers: "{{ autonomy_common_dns_rpz_primary_nameservers }}"
autonomy_common_dns_rpz_blocklist_also_notify: "{{ autonomy_common_dns_rpz_also_notify }}"
autonomy_dns_blocklist_records_present: []
autonomy_dns_blocklist_records_absent: []

# Mozilla
autonomy_common_dns_rpz_mozilla_name: "mozilla.rpz"
autonomy_common_dns_rpz_mozilla_policy: "{{ autonomy_common_dns_rpz_default_policy }}"
autonomy_common_dns_rpz_mozilla_zone_file: "db.{{ autonomy_common_dns_rpz_mozilla_name }}"
autonomy_common_dns_rpz_mozilla_zone_path: "{{ autonomy_common_dns_rpz_dir }}/{{ autonomy_common_dns_rpz_mozilla_zone_file }}"
autonomy_common_dns_rpz_mozilla_allow_query: "{{ autonomy_common_bind_allow_query }}"
autonomy_common_dns_rpz_mozilla_zone_type: "{{ autonomy_common_dns_rpz_zone_type }}"
autonomy_common_dns_rpz_mozilla_nameservers: "{{ autonomy_common_dns_rpz_primary_nameservers }}"

autonomy_common_dns_rpz_mozilla_zone:
  name: "{{ autonomy_common_dns_rpz_mozilla_name }}"
  type: "{{ autonomy_common_dns_rpz_mozilla_zone_type }}"
  file: "{{ autonomy_common_dns_rpz_mozilla_zone_file }}"
  policy: "{{ autonomy_common_dns_rpz_mozilla_policy }}"
  path: "{{ autonomy_common_dns_rpz_mozilla_zone_path }}"
  allow_query: "{{ autonomy_common_dns_rpz_mozilla_allow_query }}"
  definition: "fixed"
  nameservers: "{{ autonomy_common_dns_rpz_mozilla_nameservers }}"

autonomy_common_dns_rpz_allowlist_zone:
  name: "{{ autonomy_common_dns_rpz_allowlist_name }}"
  type: "{{ autonomy_common_dns_rpz_allowlist_zone_type }}"
  file: "{{ autonomy_common_dns_rpz_allowlist_zone_file }}"
  policy: "{{ autonomy_common_dns_rpz_allowlist_policy }}"
  path: "{{ autonomy_common_dns_rpz_allowlist_zone_path }}"
  allow_query: "{{ autonomy_common_dns_rpz_allowlist_allow_query }}"
  definition: "dynamic"
  nameservers: "{{ autonomy_common_dns_rpz_allowlist_nameservers }}"
  also_notify: "{{ autonomy_common_dns_rpz_allowlist_also_notify }}"
  records_present: "{{ autonomy_dns_allowlist_records_present }}"
  records_absent: "{{ autonomy_dns_allowlist_records_absent }}"

autonomy_common_dns_rpz_redirectlist_zone:
  name: "{{ autonomy_common_dns_rpz_redirectlist_name }}"
  type: "{{ autonomy_common_dns_rpz_redirectlist_zone_type }}"
  file: "{{ autonomy_common_dns_rpz_redirectlist_zone_file }}"
  policy: "{{ autonomy_common_dns_rpz_redirectlist_policy }}"
  path: "{{ autonomy_common_dns_rpz_redirectlist_zone_path }}"
  allow_query: "{{ autonomy_common_dns_rpz_redirectlist_allow_query }}"
  definition: "dynamic"
  nameservers: "{{ autonomy_common_dns_rpz_redirectlist_nameservers }}"
  also_notify: "{{ autonomy_common_dns_rpz_redirectlist_also_notify }}"
  records_present: "{{ autonomy_dns_redirectlist_records_present }}"
  records_absent: "{{ autonomy_dns_redirectlist_records_absent }}"

autonomy_common_dns_rpz_blocklist_zone:
  name: "{{ autonomy_common_dns_rpz_blocklist_name }}"
  type: "{{ autonomy_common_dns_rpz_blocklist_zone_type }}"
  file: "{{ autonomy_common_dns_rpz_blocklist_zone_file }}"
  policy: "{{ autonomy_common_dns_rpz_blocklist_policy }}"
  path: "{{ autonomy_common_dns_rpz_blocklist_zone_path }}"
  allow_query: "{{ autonomy_common_dns_rpz_blocklist_allow_query }}"
  definition: "dynamic"
  nameservers: "{{ autonomy_common_dns_rpz_blocklist_nameservers }}"
  also_notify: "{{ autonomy_common_dns_rpz_blocklist_also_notify }}"
  records_present: "{{ autonomy_dns_blocklist_records_present }}"
  records_absent: "{{ autonomy_dns_blocklist_records_absent }}"

autonomy_common_dns_rpz_basic_zones:
  - "{{ autonomy_common_dns_rpz_allowlist_zone }}"
  - "{{ autonomy_common_dns_rpz_redirectlist_zone }}"
  - "{{ autonomy_common_dns_rpz_mozilla_zone }}"
  - "{{ autonomy_common_dns_rpz_blocklist_zone }}"

autonomy_common_dns_rpz_zones: "{{ autonomy_common_dns_rpz_basic_zones + autonomy_common_dns_rpz_hagezi_zones }}"

# Example Allowlist
# autonomy_dns_allowlist_records_present:
#   - domain: "*.doubleclick.net"
#     alias:  "rpz-passthru."

# Example Redirectlist
# autonomy_dns_redirectlist_records_present:
#   - domain: "*.doubleclick.net"
#     alias:  "example.com"
#   - domain: "*.pubmatic.com"
#     ipv4:   "127.0.0.1"
#   - domain: "*.mopub.com"
#     ipv6:   "::1"

# Example Blocklist
# autonomy_dns_blocklist_records_present:
#   - domain: "*.doubleclick.net"
#   - domain: "*.pubmatic.com"
#   - domain: "*.mopub.com"
#   - domain: "*.eskimi.com"
#   - domain: "*.adcolony.xyz"
#   - domain: "*.adsrvr.org"
#   - domain: "*.adsymptotic.com"
#   - domain: "*.servedby-buysellads.com"
#   - domain: "srv.buysellads.com"
#   - domain: "*.powerinboxedge.com"
#   - domain: "*.defof.com"
#   - domain: "*.licasd.com"
#   - domain: "*.liadm.com"
