---
# ==================================================================================================
#
# This is used to create user dotfiles for both the host's local users and domain controlled users.
# Any tasks that are set "item.id_number >= autonomy_min_domain_id_number" is for domain users only.
#
# ==================================================================================================
- name: "Ensure User Home directory exists."
  ansible.builtin.file:
    dest: "{{ __dotfiles_home }}"
    state: directory
    owner: "{{ __dotfiles_owner }}"
    group: "{{ __dotfiles_group }}"
    mode: "{{ __mode }}"
  loop: "{{ autonomy_users_dotfiles_users }}"
  become: true
  vars:
    __dotfiles_home: "{{ item['unix_home'] | default(__dotfiles_default_home) }}"
    __dotfiles_owner: "{{ cifs_owner | default(item['id_number']) }}"
    __dotfiles_group: "{{ cifs_group | default(item['id_number']) }}"
    __mode: "{{ cifs_dir_mode | default(autonomy_users_dotfiles_mode) }}"
    __dotfiles_default_home: "{{ autonomy_users_dotfiles_home + '/' + item['username'] }}"
  when:
    - item.username is defined
    - item.id_number is defined
    - (item.login_shell is not defined) or (item.login_shell != "/usr/sbin/nologin")

- name: "Install User gitconfig."
  ansible.builtin.template:
    src: "home/gitconfig.j2"
    dest: "{{ __dotfiles_home }}/.gitconfig"
    owner: "{{ __dotfiles_owner }}"
    group: "{{ __dotfiles_group }}"
    mode: "0644"
  loop: "{{ autonomy_users_dotfiles_users }}"
  become: true
  vars:
    __dotfiles_home: "{{ item['unix_home'] | default(__dotfiles_default_home) }}"
    __dotfiles_owner: "{{ cifs_owner | default(item.id_number) }}"
    __dotfiles_group: "{{ cifs_group | default(item.id_number) }}"
    __mode: "{{ cifs_file_mode | default(autonomy_user_dotfiles_mode) }}"
    __dotfiles_default_home: "{{ autonomy_users_dotfiles_home + '/' + item.username }}"
  when:
    - item.id_number is defined
    - (item.shell is not defined) or (item.shell != "/usr/sbin/nologin")

# ==================================================================================================
#
# Autostart Configuration
#
# ==================================================================================================
- name: "Ensure User ~/.config/autostart directory exists."
  ansible.builtin.file:
    dest: "{{ __dotfiles_home }}/.config/autostart"
    state: directory
    owner: "{{ __dotfiles_owner }}"
    group: "{{ __dotfiles_group }}"
    mode: "{{ __mode }}"
  loop: "{{ autonomy_users_dotfiles_users }}"
  become: true
  vars:
    __dotfiles_home: "{{ item['unix_home'] | default(__dotfiles_default_home) }}"
    __dotfiles_owner: "{{ cifs_owner | default(item.id_number) }}"
    __dotfiles_group: "{{ cifs_group | default(item.id_number) }}"
    __mode: "{{ cifs_dir_mode | default(autonomy_users_dotfiles_mode) }}"
    __dotfiles_default_home: "{{ autonomy_users_dotfiles_home + '/' + item.username }}"
    __dotfiles_autostart_dir: "{{ item['autostart_dir'] | default(false) }}"
  when:
    - item.username is defined
    - item.id_number is defined
    - (item.login_shell is not defined) or (item.login_shell != "/usr/sbin/nologin")
    - (item.id_number | int) >= autonomy_users_managed_min_id or __dotfiles_autostart_dir

- name: "Configure User SSH."
  include_tasks: "config_dotfiles_ssh.yml"

# - name: "Configure User GnuPG."
#   include_tasks: "config_dotfiles_gnupg.yml"

- name: "Configure User Git Repos."
  include_tasks: "config_git_repos.yml"
  loop: "{{ autonomy_users_dotfiles_users }}"
  loop_control:
    loop_var: user
    index_var: user_index

#  LocalWords:  repos gnupg
