---
# ==================================================================================================
#
# NOTE: This task requires 'ansible.builtin.shell'; 'ansible.builtin.command' get's a non-zero
#       return code.
#
# ==================================================================================================
- name: "Identify user gpg key."
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      gpg -K |
      grep -v expired |
      grep -v revoked |
      awk '/sec/{if (length($2) > 0) print $2}' |
      sed 's|.*/0x||'
  loop: "{{ autonomy_users_password_store_users }}"
  become: true
  become_user: "{{ item['username'] }}"
  register: user_gpg_keys

- name: "Print User GPG Keys."
  ansible.builtin.debug:
    msg: "{{ user_gpg_keys }}"

- name: "Initiallize user password store."
  ansible.builtin.command:
    cmd: "pass init {{ item['stdout_lines'][0] }}"
    creates: "{{ autonomy_users_password_store_gpg_id_path }}"
  loop: "{{ user_gpg_keys['results'] }}"
  become: true
  become_user: "{{ item['item']['username'] }}"
  vars:
    __autonomy_users_loopvar_username: "{{ item['item']['username'] }}"
