---
# ==================================================================================================
#
# Download User Git Repos
#
# ==================================================================================================

# ==================================================================================================
#
# Determine if Specified directory is a git repo
#
# ==================================================================================================


# ==================================================================================================
#
# If it's not a git repo, remove it.
#
# ==================================================================================================
# - name: "Remove Repo Directory (Since it is not a git repo)."
#   file:
#     dest: "{{ __dest }}"
#     state: absent
#   loop: "{{ user['git_repos'] }}"
#   vars:
#     ansible_user: "{{ user['username'] }}"
#     __dest: "{{ user['unix_home'] }}/{{ item[0]['dest'] }}"
#   when:
#     - item[0]['repo'] is defined
#     - item[0]['repo'] is truthy
#     - result is falsy

- name: "[1st Pass] Ensure repo directory exists for: {{ user['username'] }}"
  ansible.builtin.file:
    path: "{{ __dest }}"
    owner: "{{ user['id_number'] }}"
    group: "{{ user['id_number'] }}"
    mode: "0755"
    state: "directory"
  loop: "{{ user['git_repos'] }}"
  vars:
    ansible_user: "{{ user['username'] }}"
    __dest: "{{ user['unix_home'] }}/{{ item[0]['dest'] }}"
  when:
    - item[0]['repo'] is defined
    - item[0]['repo'] is truthy
    - (item[0]['second_pass'] is not defined) or (item[0]['second_pass'] is falsy)

- name: "[1st Pass] Update repos for: {{ user['username'] }}"
  ansible.builtin.git:
    repo: "{{ item[0]['repo'] }}"
    dest: "{{ __dest }}"
    update: "{{ item[0]['update'] }}"
    remote: "{{ item[0]['remote'] }}"
    version: "{{ item[0]['version'] | default('main') }}"
    accept_newhostkey: true
    force: false
  loop: "{{ user['git_repos'] }}"
  vars:
    ansible_user: "{{ user['username'] }}"
    __dest: "{{ user['unix_home'] }}/{{ item[0]['dest'] }}"
  when:
    - item[0]['repo'] is defined
    - item[0]['repo'] is truthy
    - (item[0]['second_pass'] is not defined) or (item[0]['second_pass'] is falsy)

# Allow a second pass for repos that are inside a folder in another repo
# Useful for things like private config repos within a spacemacs repo.
- name: "[2nd Pass] Ensure repo directory exists for: {{ user['username'] }}"
  ansible.builtin.file:
    path: "{{ __dest }}"
    owner: "{{ user['id_number'] }}"
    group: "{{ user['id_number'] }}"
    mode: "0755"
    state: "directory"
  loop: "{{ user['git_repos'] }}"
  vars:
    __dest: "{{ user['unix_home'] }}/{{ item[0]['dest'] }}"
    ansible_user: "{{ user['username'] }}"
  when:
    - item[0]['repo'] is defined
    - item[0]['repo'] is truthy
    - item[0]['second_pass'] is defined
    - item[0]['second_pass'] is truthy

- name: "[2nd Pass] Update repos for: {{ user['username'] }}"
  ansible.builtin.git:
    repo: "{{ item[0]['repo'] }}"
    dest: "{{ __dest }}"
    update: "{{ item[0]['update'] }}"
    remote: "{{ item[0]['remote'] }}"
    version: "{{ item[0]['version'] | default('main') }}"
    accept_newhostkey: true
    force: false
  loop: "{{ user['git_repos'] }}"
  vars:
    ansible_user: "{{ user['username'] }}"
    __dest: "{{ user['unix_home'] }}/{{ item[0]['dest'] }}"
  when:
    - item[0]['repo'] is defined
    - item[0]['repo'] is truthy
    - item[0]['second_pass'] is defined
    - item[0]['second_pass'] is truthy
