---
- name: "Include OS-specific variables."
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false

- name: "Configure System Users."
  include_tasks: "users_local.yml"
  when:
    - __user_tasks == "local_users"

- name: "Configure User Password Store."
  include_tasks: "config_password_store.yml"
  when:
    - __user_tasks == "passwordstore"

- name: "Configure User Dotfiles."
  include_tasks: "config_dotfiles.yml"
  when:
    - __user_tasks == "dotfiles"

- name: "Configure Realm Users."
  include_tasks: "users_realm.yml"
  when:
    - __user_tasks == "realm_users"
