---
- name: "Include Family Tasks."
  include_tasks: "users_local_{{ ansible_os_family | lower }}.yml"
  when:
    - ansible_network_os is not defined
    - inventory_hostname not in groups["vendor_managed"]

- name: "Include NetworkOS tasks."
  include_tasks: "users_local_{{ ansible_network_os.split('.')[2] | lower }}.yml"
  when:
    - ansible_network_os is defined
