---
# tasks file for sudo
# ==================================================================================================
#
# Enable sudo
#
# ...
#
# ==================================================================================================
- name: Setup Master Sudoers file
  ansible.builtin.template:
    src: "sudoers.j2"
    dest: "{{ autonomy_common_sysconf_dir }}/sudoers"
    owner: root
    group: root
    mode: "0640"
    validate: /usr/sbin/visudo -csf %s
  become: true
  tags:
    - sudo
    - sudo_debug
    - sudo-debug
