---
# roles/bind/defaults/main.yml
autonomy_bind_packages:
  - python3-netaddr
  - python3-dnspython
  - "{{ autonomy_common_bind_package }}"
  - bind9utils

#autonomy_bind_ipv6_reversezones: []

autonomy_bind_zone_samba_controlled: false

# Directories
autonomy_bind_conf_dir: "{{ autonomy_common_sysconf_dir }}/bind"
autonomy_bind_key_dir: "{{ autonomy_bind_conf_dir }}/keys"
autonomy_bind_log_dir: "{{ autonomy_common_log_dir }}/bind"
autonomy_bind_cache_dir: "{{ autonomy_common_cache_dir }}/bind"
# autonomy_bind_geoip-directory ( <quoted_string> | none );
# autonomy_bind_key-directory <quoted_string>;
# autonomy_bind_managed-keys-directory <quoted_string>;
# autonomy_bind_new-zones-directory <quoted_string>;

# Files
autonomy_bind_auth_file: "auth_transfer.conf"
autonomy_bind_config_file: "named.conf"
autonomy_bind_default_zone_file: "named.conf.root-hints"
autonomy_bind_local_file: "named.conf.local"
autonomy_bind_logging_file: "named.conf.log"
autonomy_bind_options_file: "named.conf.options"
autonomy_bind_rpz_file: "named.conf.rpz"
autonomy_bind_log: "data/named.run"
autonomy_bind_session_key_file: "session.key"
autonomy_bind_pid_file: "{{ autnoomy_common_run_dir }}/named/named.pid"
autonomy_bind_bindkeys_file: "{{ autonomy_common_sysconf_dir }}/named.iscdlv.key"
# autonomy_bind_dump-file <quoted_string>;
# autonomy_bind_memstatistics-file <quoted_string>;
# autonomy_bind_statistics-file <quoted_string>;
# autonomy_bind_secroots-file <quoted_string>;
# autonomy_bind_recursing-file <quoted_string>;
# autonomy_bind_session-keyfile ( <quoted_string> | none );

# Paths
autonomy_bind_auth_path: "{{ autonomy_bind_conf_dir }}/{{ autonomy_bind_auth_file }}"
autonomy_bind_config_path: "{{ autonomy_bind_conf_dir }}/{{ autonomy_bind_config_file }}"
autonomy_bind_default_zone_path: "{{ autonomy_bind_conf_dir }}/{{ autonomy_bind_default_zone_file }}"
autonomy_bind_local_path: "{{ autonomy_bind_conf_dir }}/{{ autonomy_bind_local_file }}"
autonomy_bind_logging_path: "{{ autonomy_bind_conf_dir }}/{{ autonomy_bind_logging_file }}"
autonomy_bind_options_path: "{{ autonomy_bind_conf_dir }}/{{ autonomy_bind_options_file }}"
autonomy_bind_rpz_path: "{{ autonomy_bind_conf_dir }}/{{ autonomy_bind_rpz_file }}"
autonomy_bind_root_zone_path: "{{ autonomy_bind_cache_dir }}/db.root"
autonomy_bind_root_hints_path: "{{ autonomy_common_data_dir }}/dns/root.hints"
autonomy_bind_session_key_path: "{{ autonomy_common_run_dir }}/named/{{ autonomy_bind_session_key_file }}"

# URLs
autonomy_bind_root_hints_url: "https://www.internic.net/domain/named.root"
autonomy_bind_root_zone_url: "https://www.internic.net/domain/root.zone"


autonomy_bind_dir_mode: "0755"
autonomy_common_bind_zone_dir_mode: "0775"
autonomy_bind_log_dir_mode: "0770"

autonomy_bind_file_mode: "0644"
autonomy_bind_zone_file_mode: "{{ autonomy_bind_file_mode }}"

autonomy_bind_config_files:
  - "{{ autonomy_bind_config_file }}"
  - "{{ autonomy_bind_default_zone_file }}"
  - "{{ autonomy_bind_local_file }}"
  - "{{ autonomy_bind_logging_file }}"
  - "{{ autonomy_bind_options_file }}"

# Commands
autonomy_bind_ddns_confgen: "{{ autonomy_common_syscmd_dir }}/ddns-confgen"

autonomy_bind_dyndns_secret: "secret"
autonomy_bind_ddns_algorithm: "hmac-sha512"


# Key bindings
autonomy_bind_dns_keys: []
#  - name: master_key
#    algorithm: hmac-sha256
#    secret: "password"


# statistics channels configuration
autonomy_bind_statistics_channels: false
autonomy_bind_statistics_port: 8053
autonomy_bind_statistics_host: 127.0.0.1
autonomy_bind_statistics_allow:
  - "127.0.0.1"

autonomy_bind_extra_include_files: []

# File mode for master zone files (needs to be something like 0660 for dynamic updates)

autonomy_bind9_bogusnet_acl:
  name: "bogusnet"
  networks:
    - 0.0.0.0/8
    - 192.0.2.0/24
    - 224.0.0.0/3
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

autonomy_bind9_myipv4_acl:
  name: myipv4
  networks:
    - 127.0.0.1
    - "{{ ansible_host }}"

autonomy_bind9_myipv6_acl:
  name: "myipv6"

# ==================================================================================================
#
# System Defaults
#
# ==================================================================================================
__bind_ddns_zones: []
__complete_bind_dns_zones: []
__bind_dns_zone_samba_domain: no
__tmp_keyfiles: []

__autonomy_bind_zone_directories:
  - name: "{{ autonomy_common_bind_zone_dir }}"
    mode: "{{ autonomy_common_bind_zone_dir_mode }}"
  - name: "{{ autonomy_bind_cache_dir }}"
    mode: "{{ autonomy_common_bind_zone_dir_mode }}"
  - name: "{{ autonomy_bind_log_dir }}"
    mode: "{{ autonomy_bind_log_dir_mode }}"

__bind_bin_dir: "/usr/bin"
__bind_named_checkconf: "{{ __bind_bin_dir }}/named-checkconf"
__bind_named_checkzone: "{{ __bind_bin_dir }}/named-checkzone"
