---
autonomy_bind_rpz_enabled: false

autonomy_bind_rpz_zones:
  - name: "mozilla.rpz"
    type: "primary"
    zonefile: "db.mozilla.rpz"
    break_dnssec: "yes"



#{ zone <string> [ add-soa <boolean> ] [ log <boolean> ] [ max-policy-ttl <duration> ] [ min-update-interval <duration> ] [ policy ( cname | disabled | drop | given | no-op | nodata | nxdomain | passthru | tcp-only <quoted_string> ) ] [ recursive-only <boolean> ] [ nsip-enable <boolean> ] [ nsdname-enable <boolean> ] [ ede <string> ]; ... } [ add-soa <boolean> ] [ break-dnssec <boolean> ] [ max-policy-ttl <duration> ] [ min-update-interval <duration> ] [ min-ns-dots <integer> ] [ nsip-wait-recurse <boolean> ] [ nsdname-wait-recurse <boolean> ] [ qname-wait-recurse <boolean> ] [ recursive-only <boolean> ] [ servfail-until-ready <boolean> ] [ nsip-enable <boolean> ] [ nsdname-enable <boolean> ] [ dnsrps-enable <boolean> ] [ dnsrps-options { <unspecified-text> } ];

# RPZ / RPS
# autonomy_bind_dnsrps-enable <boolean>; // obsolete
# autonomy_bind_dnsrps-library <quoted_string>; // obsolete
# autonomy_bind_dnsrps-options { <unspecified-text> }; // obsolete
