---
autonomy_bind_rpz_break_dnssec: "yes"

# RPZ / RPS
# autonomy_bind_dnsrps-enable <boolean>; // obsolete
# autonomy_bind_dnsrps-library <quoted_string>; // obsolete
# autonomy_bind_dnsrps-options { <unspecified-text> }; // obsolete
