---
autonomy_bind_zone_domains:
  - name: "example.com"
    hostmaster_email: "hostmaster"
    networks:
      - "10.0.2"


# SOA information
autonomy_bind_zone_time_to_refresh: "1D"
autonomy_bind_zone_time_to_retry: "1H"
autonomy_bind_zone_time_to_expire: "1W"
autonomy_bind_zone_minimum_ttl: "1D"
autonomy_bind_zone_ttl: "604800"
autonomy_bind_zone_refresh: "604800"
autonomy_bind_zone_retry: "86400"
autonomy_bind_zone_expire: "2419200"
autonomy_bind_zone_negative_cache_ttl: "604800"

autonomy_bind_zone_soa: "{{ groups[autonomy_common_zone_name + '_dns_servers'][0] }}"
autonomy_bind_zone_admin: "{{ autonomy_common_sysadmin_user }}.{{ autonomy_common_zone_domain }}"
autonomy_bind_zone_serial_number: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}00"
autonomy_bind_reverse_zone_serial_number: "{{ autonomy_bind_zone_serial_number }}"
autonomy_bind_ipv6_reversezone_serial_number: "{{ autonomy_bind_reverse_zone_serial_number }}"
