---
# tasks file for fail2ban
# ======================================================================
#
# Tasks:
#
#
# ======================================================================
- name: Include OS-specific variables.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false

- name: "Install fail2ban packages."
  ansible.builtin.package:
    name: "{{ autonomy_fail2ban_packages }}"
    state: present
  become: true
