galaxy_info:
  author: G Derber
  description: Recurring Maintenance tasks for a site.
  company: Bloodymage

  issue_tracker_url: http://github.com/bloodymage/ansible-collection-autonomy

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Debian
      versions:
        - 13

  galaxy_tags:
    - bloodymage
    - maintenance
    - upgrade
    - dns

dependencies:
  - role: bloodymage.autonomy.common
