---
- name: "Include OS-specific variables."
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false
  tags:
    - install-packages
    - opensc

- name: "Install packages."
  ansible.builtin.package:
    name: "{{ autonomy_opensc_packages }}"
    state: present
  become: true
  tags:
    - install-packages
    - opensc
