---
# defaults file for clamav
autonomy_clamav_packages:
  - arj
  - bzip2
  - cabextract
  - clamav
  - clamav-milter
  - cpio
  - file
  - gzip
  - lzop
  - nomarch
  - p7zip
  - pax
  - rpm
  - unzip
  - zip
  - zoo

autonomy_clamav_milter_socket: "/var/spool/postfix/clamav/clamav-milter.ctl"
autonomy_clamav_on_infected: "Quarantine"
autonomy_clamav_log_facility: "LOG_MAIL"
