galaxy_info:
  author: G Derber
  description: Installs an Apache Web Server
  company: Bloodymage

  issue_tracker_url: http://github.com/bloodymage/ansible-collection-autonomy

  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Debian
      versions:
        - 13

  galaxy_tags:
    - bloodymage
    - servers
    - server
    - webservers
    - apache

dependencies:
  - role: bloodymage.autonomy.common
