---
# tasks file for htop
- name: "Include OS-specific variables."
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false

- name: "Install htop packages."
  ansible.builtin.package:
    name: "{{ autonomy_htop_packages }}"
    state: present
  become: true
  when:
    - autonomy_htop_enabled

- name: "Remove htop packages."
  ansible.builtin.package:
    name: "{{ autonomy_htop_packages }}"
    state: absent
  become: true
  when:
    - not autonomy_htop_enabled
