---
# Configure Hosts that require acmeca
- name: "Run Acme CA Account Playbook."
  import_playbook: acmeca_account.yml

- name: "Run ACME CA Host Certificates Playbook."
  import_playbook: acmeca_certs.yml
