---
- name: "ACME CA Account Playbook."
  hosts: localhost
  tasks:
    - name: "Include ACMECA role."
      ansible.builtin.include_role:
        name: bloodymage.autonomy.acmeca
      vars:
        __acmeca_tasks: "account"
      tags:
        - acmeca
        - acmeca-test
        - acmeca-account
