---
# ==================================================================================================
#
# Gather some information.  This is always done, as it'll create groups used later in this playbook.
#
# ==================================================================================================
- name: "Gather facts for Mikrotik devices."
  gather_facts: false
  hosts: mikrotik
  tasks:
    - name: "Retrieve facts"
      community.routeros.facts:
        gather_subset: all

# - name: "Configure the environment for basic host configuration."
#   hosts: vendor_managed
#   ignore_unreachable: yes
#   roles:
#     - role: bloodymage.autonomy.autoconfig
#       tags:
#         - always

- name: "Configure the environment for basic host configuration."
  hosts: all:!localhost:!vendor_managed:!dns_only
  ignore_unreachable: yes
  roles:
    - role: bloodymage.autonomy.autoconfig
      tags:
        - always

- name: "Upgrade All hosts."
  hosts: all:!localhost:!public_zone:!virtual_hosts:!dns_only
  roles:
    - role: bloodymage.autonomy.maintenance
      vars:
        __maintenance_tasks: "upgrade"
      when:
        - autonomy_virtual_host is falsy
        - ansible_connection != "local"
      tags:
        - upgrade

- import_playbook: "all_linux_init.yml"

# ==================================================================================================
#
# Configure setting applicable to ALL hosts.
#
# ==================================================================================================
- name: "Basic host configuration for all hosts."
  hosts: all:!localhost:!public_zone:!virtual_hosts:!dns_only
  strategy: linear
  roles:
    - role: bloodymage.autonomy.etc
      vars:
        __etc_tasks: "hostname"
      when:
        - autonomy_virtual_host is falsy
        - ansible_connection != "local"
        - inventory_hostname not in groups["vendor_managed"]
      tags:
        - hostname
    - role: bloodymage.autonomy.users
      vars:
        autonomy_user_dotfiles_users:
          - "{{ autonomy_users }}"
        autonomy_user_dotfiles_home: "/home"
        __user_tasks: "sysusers"
      when:
        - autonomy_users is defined
        - ansible_connection != "local"
      tags:
        - users
    - role: bloodymage.autonomy.etc
      vars:
        __etc_tasks: "hosts"
      when:
        - ansible_network_os is not defined
        - ansible_connection != "local"
        - inventory_hostname not in groups["vendor_managed"]
      tags:
        - hosts
    - role: bloodymage.autonomy.emacs
      when:
        - autonomy_emacs_enabled
        - ansible_connection != "local"
        - ansible_network_os is not defined
        - inventory_hostname not in groups["vendor_managed"]
      tags:
        - emacs
    - role: bloodymage.autonomy.unzip
      when:
        - ansible_connection != "local"
        - (autonomy_dodca_enabled or autonomy_unzip_enabled)
        - ansible_network_os is not defined
        - inventory_hostname not in groups["vendor_managed"]
      tags:
        - unzip

- name: "Install certificates on all hosts."
  hosts: all:!localhost:!public_zone:!dns_only
  roles:
    - role: bloodymage.autonomy.ownca
      vars:
        __ownca_tasks: "hostcerts"
      tags:
        - regenerate-ownca
        - ownca
        - ownca-host-certs
        - ownca-host-certificates
    - role: bloodymage.autonomy.dodca
      when:
        - ansible_connection != "local"
        - autonomy_dodca_enabled
        - inventory_hostname not in groups["vendor_managed"]
      tags:
        - dodca

- import_playbook: "all_linux.yml"
