---
# ==================================================================================================
#
# This playbook configures database servers.
#
# ==================================================================================================
# TODO: Check the hosts, should this only be database servers?
- name: "Configure environment for database server configuration."
  hosts: all:!vendor_managed
  roles:
    - role: bloodymage.autonomy.autoconfig
      tags:
        - always

- name: "Configure MariaDB Servers."
  hosts: mariadb_servers:!public_zone
  roles:
    - role: bloodymage.autonomy.mariadb
      tags:
        - mariadb

- name: "Configure Databases."
  hosts: mariadb_servers:postgresql_servers:mysql_servers
  roles:
    - role: bloodymage.autonomy.maintenance
      vars:
        __maintenance_tasks: "database"
      tags:
        - databases
        - database
