---
- name: "Install certificates on all hosts."
  hosts: all:!localhost:!public_zone:!dns_only:!vendor_managed:!virtual_hosts
  roles:
    - role: bloodymage.autonomy.dodca
      when:
        - autonomy_common_dodca_enabled
      tags:
        - dodca
