---
- name: "Prepare playbook environment."
  hosts: all:!vendor_managed
  ignore_unreachable: true
  roles:
    - role: bloodymage.autonomy.autoconfig
      tags:
        - always
    - role: bloodymage.autonomy.autoconfig
      vars:
        __env_tasks: "realm"
      tags:
        - always

# - name: "Configure Samba Fileservers."
#   hosts: samba_file_servers
#   roles:
#     - role: bloodymage.autonomy.samba
#       when:
#         - groups['samba_domain_controllers'] is not defined
#       tags:
#         - samba
#     - role: bloodymage.autonomy.samba
#       vars:
#         - __samba_tasks: acls
#       when:
#         - groups['samba_domain_controllers'] is defined
#       tags:
#         - samba-acls
#         - samba
#     - role: bloodymage.autonomy.cups
#       tags:
#         - cups

# - name: "Configure NFS Servers"
#   hosts: nfs_file_servers
#   roles:
#     - role: bloodymage.autonomy.nfsserver
#       tags:
#         - nfsserver
