---
- name: "Autoconfig All hosts."
  hosts: all
  ignore_unreachable: true
  roles:
    - role: bloodymage.autonomy.autoconfig
      tags:
        - always

- name: "Configure Databases."
  hosts: mariadb_servers:postgresql_servers:mysql_servers
  roles:
    - role: bloodymage.autonomy.maintenance
      vars:
        __maintenance_tasks: "database"
      tags:
        - databases
        - database
