---
# ==================================================================================================
#
# This playbook is for running maintenance tasks.
#
# ==================================================================================================
- hosts: all
  gather_facts: false
  serial: 1
  roles:
    - role: bloodymage.autonomy.maintenance
      vars:
        __maintenance_tasks: "wakeonlan"
      tags:
        - never
        - wakeonlan
        - wake-on-lan
    - role: bloodymage.autonomy.maintenance
      vars:
        __maintenance_tasks: "reboot"
      tags:
        - never
        - reboot

- name: "Gather facts for Mikrotik devices."
  gather_facts: false
  hosts: mikrotik
  tasks:
    - name: "Retrieve facts"
      community.routeros.facts:
        gather_subset: all
      tags:
        - always

- name: "Configure Host Connections."
  hosts: all:!localhost:!vendor_managed:!dns_only
  gather_facts: false
  roles:
    - role: bloodymage.autonomy.autoconfig
      vars:
        __env_tasks: "connections"
      tags:
        - always

- hosts: all
  ignore_unreachable: true
  roles:
    - role: bloodymage.autonomy.autoconfig
      tags:
        - always

- name: "Import Daily Maintenance Playbook."
  import_playbook: "maintenance_daily.yml"

- name: "Import Weekly Playbook."
  import_playbook: "maintenance_weekly.yml"
  when:
    - ansible_date_time.weekday == "Monday"

- name: "Import Monthly Playbook."
  import_playbook: "maintenance_monthly.yml"
  when:
    - ansible_date_time.day == "01"

- name: "Service Maintenance."
  hosts: all:!localhost
  roles:
    - role: bloodymage.autonomy.maintenance
      vars:
        __maintenance_tasks: "service restart"
      tags:
        - never
        - restart-services
