---
- name: "Configure NTP Servers."
  hosts: samba_domain_controllers:ntp_servers
  roles:
    - role: bloodymage.autonomy.ntpsec
      tags:
        - ntp
        - ntpsec

- name: "Configure NTP Clients."
  hosts: all:!samba_domain_controllers:!ntp_servers:!localhost:!vendor_managed:!virtual_hosts
  roles:
    - role: bloodymage.autonomy.systemd
      when:
        - autonomy_common_virtual_host is falsy
      vars:
        __systemd_tasks: "timesyncd"

