---
# ==================================================================================================
#
# We intentially do not set tags for config_ownca_environment because not all task are run every
# time.  That role has tags set at the task level.
#
# ==================================================================================================
- name: "Gather facts for Mikrotik devices."
  gather_facts: false
  hosts: mikrotik_routers
  tasks:
    - name: "Retrieve facts"
      community.routeros.facts:

- name: "Configure the environment for the Certificate Authorities."
  hosts: all:!dns_only
  ignore_unreachable: yes
  roles:
    - role: bloodymage.autonomy.autoconfig
      tags:
        - always
    - role: bloodymage.autonomy.autoconfig
      vars:
        __env_tasks: "ownca"
      tags: []

- name: "Setup the TLS Certificate Authorities."
  hosts: certificate_authorities
  roles:
    - role: bloodymage.autonomy.ownca
      vars:
        __ownca_tasks: "ownca"
      tags:
        - ownca
        - regenerate-ownca
    - role: bloodymage.autonomy.ownca
      vars:
        __ownca_tasks: "crls"
      tags:
        - ownca
        - regenerate-ownca
        - ownca_crl
        - ownca-crl
