---
- name: "Setup the SSH Certificate Authority."
  hosts: sshca_certificate_authorities
  roles:
    - role: bloodymage.autonomy.autoconfig
      tags:
        - always
    - role: bloodymage.autonomy.sshca
      vars:
        __sshca_tasks: "sshca"
      tags:
        - sshca
