---
- name: "Configure webservers and websites."
  hosts: webservers:!vendor_managed
  roles:
    - role: bloodymage.autonomy.autoconfig
      tags:
        - always

# ==================================================================================================
#
# We don't run this on the public zone servers, as that would be redundant.
#
# ==================================================================================================
- name: "Create Apache webservers."
  hosts: apache_servers:!public_zone:!virtual_hosts
  roles:
    - role: bloodymage.autonomy.apache
      tags:
        - apache

- name: "Create nginx webservers."
  hosts: nginx_servers:!public_zone:!virtual_hosts
  roles:
    - role: bloodymage.autonomy.nginx
      tags:
        - nginx

# ==================================================================================================
#
# This needs to go before the next group for all webservers because while this group definitely
# depends on an ACME CA working, the next group may depend on an ACME CA working.
#
# ==================================================================================================
- import_playbook: acmeca_certs.yml

- name: "Configure CRL Distribution Points."
  hosts: web_servers:&public_zone
  roles:
    - role: bloodymage.autonomy.ownca
      vars:
        __ownca_tasks: "crl_distribution"
      tags:
        - ownca-crl-distribution-points
        - ownca_crl_distribution_points
        - websites
