---
- name: "Include OS-specific variables."
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false
  tags:
    - install-packages
    - bind
    - bind-dyndns
    - bind-rpz

- name: "Install packages."
  ansible.builtin.package:
    name: "{{ autonomy_bind_packages }}"
    state: present
  become: true
  when:
    - autonomy_common_virtual_host is falsy
  tags:
    - install-packages
    - bind
    - bind-dyndns
    - bind-rpz

- name: "Ensure Zone Directories Exists and are writable by bind user."
  ansible.builtin.file:
    dest: "{{ item['name'] }}"
    state: directory
    owner: "{{ autonomy_common_bind_owner }}"
    group: "{{ autonomy_common_bind_group }}"
    mode: "{{ item['mode'] }}"
  become: true
  loop: "{{ __autonomy_bind_zone_directories }}"
  when:
    - autonomy_common_virtual_host is falsy
  tags:
    - bind
    - bind-dyndns
    - bind-rpz

- name: "Configure Dynamic DNS Keys."
  include_tasks: dynamic_dns.yml
  tags:
    - bind
    - bind-dyndns
    - bind-dyndns-force-key-change

- name: "Configure Dynamic RPZ Keys."
  include_tasks: dynamic_rpz.yml
  when:
    - autonomy_common_dns_rpz_enabled
    - inventory_hostname not in groups['samba_domain_controllers'] | default([])
  tags:
    - bind
    - bind-dynrpz
    - bind-dynrpz-force-key-change

- name: "Configure RPZ."
  include_tasks: "rpz.yml"
  when:
    - autonomy_common_dns_rpz_enabled
    - inventory_hostname not in groups['samba_domain_controllers'] | default([])
  tags:
    - bind
    - bind-rpz

- name: "Configure Bind."
  include_tasks: config.yml
  tags:
    - bind
    - bind-dyndns
    - bind-rpz

# ==================================================================================================
#
# Flush the handlers (restart bind9) to ensure bind is running with the current configuration. This
# fixes a problem where the root dns zone file can not be downloaded because bind is not running,
# which causes dns lookup errors on the next step.
#
# It also will cause the play to end for any host that has an invalid configuration right away.
#
# ==================================================================================================
- name: "Ensure bind is up and running."
  ansible.builtin.meta: flush_handlers

- name: "Configure Zones."
  include_tasks: "zones.yml"
  tags:
    - bind
    - bind-zones
