---
# ==================================================================================================
#
# OS Specific Setup
#
#
# ==================================================================================================
- name: "Include OS-specific variables."
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ __os_variables_files }}"
      paths:
        - "vars"
  become: false
  when:
    - autonomy_virtual_host is falsy
    - inventory_hostname not in groups['public_zone'] | default([])

- name: "Install packages."
  ansible.builtin.package:
    name: "{{ autonomy_bind_packages }}"
    state: present
  become: true
  when:
    - autonomy_virtual_host is falsy
    - inventory_hostname not in groups['public_zone'] | default([])

# ==================================================================================================
#
# This creates the following directories:
#   - /var/lib/bind/
#   - /var/cache/bind/
#
# These are set 0775 so that the bind group can make changes.
#
# ==================================================================================================
- name: "Ensure Zone Directories Exists and are writable by bind user."
  ansible.builtin.file:
    dest: "{{ item.name }}"
    state: directory
    owner: "{{ autonomy_bind_owner }}"
    group: "{{ autonomy_bind_group }}"
    mode: "{{ item.mode }}"
  become: yes
  loop: "{{ __autonomy_bind_zone_directories }}"
  when:
    - autonomy_virtual_host is falsy
    - bind_dyndns_secret is defined
    - inventory_hostname not in groups['public_zone'] | default([])

# ==================================================================================================
#
# Set Variables
#
# ==================================================================================================
# - name: "Check bind version."
#   ansible.builtin.debug:
#     msg:
#       - "{{ ansible_facts.packages['bind9'][0]['version'] }}"
#   when: "'bind9' in ansible_facts.packages"

# ==================================================================================================
#
# The included tasks generate keys used for dynamic dns
#
# ==================================================================================================
- name: "Configure Dynamic DNS Keys."
  include_tasks: dynamic_dns.yml

- name: "Configure RPZ."
  include_tasks: "rpz.yml"
  when:
    - autonomy_bind_rpz_enabled
    - inventory_hostname not in groups['samba_domain_controllers'] | default([])

- name: "Configure Bind."
  include_tasks: config.yml

# ==================================================================================================
#
# Flush the handlers (restart bind9) to ensure bind is running with the current configuration. This
# fixes a problem where the root dns zone file can not be downloaded because bind is not running,
# which causes dns lookup errors on the next step.
#
# It also will cause the play to end for any host that has an invalid configuration right away.
#
# ==================================================================================================
- name: "Ensure bind is up and running."
  ansible.builtin.meta: flush_handlers

- name: "Configure Zones."
  include_tasks: "zones.yml"

- name: "Configure Dynamic DNS Keys."
  include_tasks: dynamic_rpz.yml
  when:
    - autonomy_bind_rpz_enabled
    - inventory_hostname not in groups['samba_domain_controllers'] | default([])
