---
- name: "Install RPZ conf file."
  ansible.builtin.template:
    src: "etc/bind/{{ autonomy_bind_rpz_file }}.j2"
    dest: "{{ autonomy_bind_rpz_path }}"
    owner: root
    group: "{{ autonomy_common_bind_group }}"
    mode: "0644"
    #validate: "{{ __bind_named_checkconf }} %s"
  become: true
  when:
    - autonomy_common_virtual_host is falsy
  notify: restart bind

- name: "Install RPZ Zonefiles (File Definition)."
  ansible.builtin.copy:
    src: "var/lib/bind/{{ item['file'] }}"
    dest: "{{ item['path'] }}"
    owner: "{{ autonomy_common_bind_owner }}"
    group: "{{ autonomy_common_bind_group }}"
    mode: "0644"
    force: false
  loop: "{{ autonomy_common_dns_rpz_zones }}"
  become: true
  when:
    - autonomy_common_dns_rpz_zones is truthy
    - item['definition'] == 'fixed'
    - autonomy_common_virtual_host is falsy

- name: "Install RPZ Zonefiles (Template definition)."
  ansible.builtin.template:
    src: "var/lib/bind/rpz.j2"
    dest: "{{ item['path'] }}"
    owner: "{{ autonomy_common_bind_owner }}"
    group: "{{ autonomy_common_bind_group }}"
    mode: "0644"
    force: false
  loop: "{{ autonomy_common_dns_rpz_zones }}"
  become: true
  when:
    - autonomy_common_dns_rpz_zones is truthy
    - item['definition'] == 'dynamic'
    - autonomy_common_virtual_host is falsy
    - item['type'] == "primary"

- name: "Check if URL sourced RPZ zonefiles exist."
  ansible.builtin.stat:
    path: "{{ item['path'] }}"
  loop: "{{ autonomy_common_dns_rpz_zones }}"
  become: false
  delegate_to: localhost
  run_once: true
  register: rpz_zone_files
  when:
    - item['url'] is defined
  tags:
    - dns
    - dns-file

- name: "Print ."
  ansible.builtin.debug:
    msg:
      - "Path: {{ item['item']['path'] }}"
      - "Url: {{ item['item']['url'] }}"
      - "Exists: {{ item['stat']['exists'] }}"
  loop: "{{ rpz_zone_files.results }}"
  when:
    - item['stat'] is defined
  tags:
    - dns
    - dns-file

- name: "Download Hagezi RPZ files."
  ansible.builtin.get_url:
    url: "{{ item['item']['url'] }}"
    dest: "{{ item['item']['path'] }}"
    owner: "{{ autonomy_common_bind_owner }}"
    group: "{{ autonomy_common_bind_group }}"
    mode: "0644"
    force: false
  loop: "{{ rpz_zone_files.results }}"
  become: true
  when:
    - autonomy_common_virtual_host is falsy
    - item['item']['type'] == "primary"
    - item['item']['url'] is defined
    - item['stat'] is not defined
  notify: restart bind
