---
# Organization Info
autonomy_common_org_name: "Example"
autonomy_common_org_unit_name: "Internal"
autonomy_common_country: ""
autonomy_common_region: ""
autonomy_common_state: "{{ autonomy_common_region }}"
autonomy_common_city: ""
