---
# ==================================================================================================
#
# Password Store Configuration
#
# ==================================================================================================
autonomy_common_password_db: "ansible"
autonomy_common_password_length: 42
autonomy_common_password_no_symbols: false
autonomy_common_password_overwrite: false

# Root Domain
autonomy_common_password_root: "{{ autonomy_common_password_db }}/{{ autonomy_common_root_domain }}"
autonomy_common_password_root_ownca: "{{ autonomy_common_password_root }}/ownca"
autonomy_common_password_root_services: "{{ autonomy_common_password_root }}/services"
autonomy_common_password_root_ext_services: "{{ autonomy_common_password_root }}/ext_services"

# Zone
autonomy_common_password_zone: "{{ autonomy_common_password_db }}/{{ autonomy_common_zone_domain }}"
autonomy_common_password_zone_ownca: "{{ autonomy_common_password_zone }}/ownca"
autonomy_common_password_zone_services: "{{ autonomy_common_password_zone }}/services"
autonomy_common_password_zone_ext_services: "{{ autonomy_common_password_zone }}/ext_services"

# Host
autonomy_common_password_hosts: "{{ autonomy_common_password_zone }}/hosts"
autonomy_common_password_host: "{{ autonomy_common_password_hosts }}/{{ inventory_hostname_short }}"
autonomy_common_password_host_services: "{{ autonomy_common_password_host }}/services"
autonomy_common_password_host_ext_services: "{{ autonomy_common_password_host }}/ext_services"

# Users
autonomy_common_password_domain_users: "{{ autonomy_common_password_zone }}/domain_users"

# Default Passwords
autonomy_mediawiki_db_password: "password"
autonomy_mysql_administrator_password: "password"
autonomy_mysql_system_maintenance_user_password: "password"
autonomy_nextcloud_db_password: "password"
autonomy_samba_administrator_password: "password"
