---
# ==================================================================================================
#
# Password Store Configuration
#
# ==================================================================================================
autonomy_common_password_db: "ansible"
autonomy_common_password_length: 42
autonomy_common_password_no_symbols: false
autonomy_common_password_overwrite: false

# Root Domain
autonomy_common_password_root: "{{ autonomy_common_password_db }}/{{ autonomy_common_root_domain }}"
autonomy_common_password_root_ownca: "{{ autonomy_common_password_root }}/ownca"
autonomy_common_password_root_services: "{{ autonomy_common_password_root }}/services"
autonomy_common_password_root_external_services: "{{ autonomy_common_password_root }}/external_services"

# Zone
autonomy_common_password_zone: "{{ autonomy_common_password_db }}/{{ autonomy_common_zone_domain }}"
autonomy_common_password_hosts: "{{ autonomy_common_password_zone }}/hosts"
autonomy_common_password_host: "{{ autonomy_common_password_host }}/{{ inventory_hostname_short }}"
autonomy_common_password_ownca: "{{ autonomy_common_password_zone }}/ownca"
autonomy_common_password_services: "{{ autonomy_common_password_zone }}/services"
autonomy_common_password_external_services: "{{ autonomy_common_password_zone }}/external_services"

# Default Passwords
autonomy_mediawiki_db_password: "password"
autonomy_mysql_administrator_password: "password"
autonomy_mysql_system_maintenance_user_password: "password"
autonomy_nextcloud_db_password: "password"
autonomy_samba_administrator_password: "password"
